### ISSUE TITLE
Add contact users to personal filtering community

### ISSUE THREAD

**Issue by olmari** [tulir/mautrix-whatsapp#102]
Feature request:

Matrix-community -style user/chatlist (whichever possible) for whatsapp in ones contact list. Basically same thing that mautrix-facebook implements.

**Comment by tulir** [comment]
[Personal filtering communities](https://github.com/tulir/mautrix-whatsapp/blob/master/example-config.yaml#L57-L60) are already implemented (they were here before mautrix-facebook and mautrix-hangouts), but the difference is that contact users don't get added, only rooms do.

**Comment by tulir** [comment]
I think contact users are added now too
