### ISSUE TITLE
tulir/mautrix-whatsapp: Error getting image: manifest for tulir/mautrix-whatsapp:latest not found 

### ISSUE THREAD

**Issue by Yalman** [tulir/mautrix-whatsapp#103]
Hi,

i receive this error if i try to download the docker image via debian cockpit with container pugin (arm).

Regards

**Comment by mawalu** [comment]
The image moved from docker hub to https://dock.mau.dev/tulir/mautrix-whatsapp, had the same problem but found the note on the [hub page](https://hub.docker.com/r/tulir/mautrix-whatsapp)
