### ISSUE TITLE
Don't show unneccesary connection erros on botuser

### ISSUE THREAD

**Issue by olmari** [tulir/mautrix-whatsapp#107]
There is couple of recurring connection erros that bot reports to (matrix) user that I think isn't really an errors that needs reporting or any kind of solving... For example:

```
Your WhatsApp connection failed: websocket: close 1006 (abnormal closure): unexpected EOF. Reconnecting...
Reconnected successfully
```

and

```
Your WhatsApp connection failed: read tcp [IPv6:addr:here]:33348->[anot:her:IPv6:addr:here]:443: read: connection reset by peer. Reconnecting...
Reconnected successfully
```

Where reconnect happends in sub-second time.

I _think_ these type of errors, especially the 1006 one, is more of WA servers rotating, booting, switching, doing whatever not-really-error thing. I suggest that bridge would only report anything if reconnection is _not_ successfull on these types of things, rather than immediately tell connection fail and reconnection successful in less than a second. Either we figure out for what errors to wait if reconnect fail, or do it generally for all (similar) errors.

With that all the errors would still get reported if leading to not working state, but simple connection hiccup or timed rotation doesn't generate meaningless error.

**Comment by tulir** [comment]
https://github.com/tulir/mautrix-whatsapp/blob/master/example-config.yaml#L98-L100
