### ISSUE TITLE
Many mysterious "crashes" recently

### ISSUE THREAD

**Issue by Ezwen** [tulir/mautrix-whatsapp#109]
For some time I had been running the bridge without any problem, but recently since an update I made (I can't remember when) the bridge has been existing (or crashing ?) quite a lot.

In the logs I can only see this, which means the bridge shut downs cleanly (but without me asking for it):
```
nov. 17 20:15:37 hallownest 1f6b0bcd1ece[19748]: [Nov 17, 2019 19:15:37] [INFO] Interrupt received, stopping...
nov. 17 20:15:37 hallownest 1f6b0bcd1ece[19748]: [Nov 17, 2019 19:15:37] [DEBUG] Disconnecting @xxx:yyy.zzz
nov. 17 20:15:37 hallownest 1f6b0bcd1ece[19748]: [Nov 17, 2019 19:15:37] [Matrix/DEBUG] Listener stopped.
nov. 17 20:15:37 hallownest 1f6b0bcd1ece[19748]: [Nov 17, 2019 19:15:37] [INFO] Bridge stopped.
```

And thus I have to manually restart my bridge once in a while, and I don't understand why…

Any idea? :(

**Comment by tulir** [comment]
> Interrupt received, stopping...

That means it's receiving a SIGTERM or SIGINT. I'm pretty sure it doesn't do false positives, so the most likely situation is that something in your environment is sending those signals.

**Comment by Ezwen** [comment]
Thanks for your answer :). Indeed it must come from somewhere else, you are right… I just wanted to make sure something obvious could be the culprit. I suspect that my problem is caused by ouroboros that automatically updates the docker image once in a while on my system − but it is still strange because it is supposed to restart/recreate the container once updated, instead of simply shutting it down.

Anyway, I'll close this then! Cheers
