### ISSUE TITLE
Starting PM with people in group

### ISSUE THREAD

**Issue by PureTryOut** [tulir/mautrix-whatsapp#110]
Recently I've had to start a PM with someone in a shared group chat. I expected to be able to do this by just clicking on the user in Riot, and inviting them to a chat from there. However, this was not the case and the bridge didn't accept the invite. I had to copy over the phonenumber and run `pm <international phone number>` in the bridge management room to start a chat instead.

Please allow starting chats with people that already have a Matrix representative but you don't have a chat open with yet.

**Comment by MelvinGr** [comment]
Same thing happening to me, bot won't accept chat invites

**Comment by PureTryOut** [comment]
Next time please use Github's :+1: rather than bumping the thread, thanks!
