### ISSUE TITLE
Unable to scan code running WhatsApp in Android VM

### ISSUE THREAD

**Issue by alistair23** [tulir/mautrix-whatsapp#111]
I can't get the QR code generated by mautrix-whatsapp to work with WhatsApp running in an Android VM.

I am running the latest version from here: https://www.whatsapp.com/android/?_fb_noscript=1, version `2.19.342` and it just gives me this error:

> Couldn't scan code. Make sure you are on web.whatsapp.com and scan again

The app inside the VM using a virtual webcam can connect with web.whatsapp.com, so the setup should be fine. Any ideas?

**Comment by magiruuvelvet** [comment]
Scanning the QR code inside an Android VM is a bit tricky but it works. I only got it to work with the "Virtual Scene" mode from the official AVD emulator from Android Studio. I don't think an emulated web cam works, at least using the `v4l2loopback` kernel module didn't work for me - other programs throw errors too attempting to open the device.

**Comment by alistair23** [comment]
I managed to get `v4l2loopback` working. It's just really tricky.

I am going to send a PR with an update to the documentation about my experience, as I think the documentation skips a few steps :)

**Comment by cubimon** [comment]
I spent so much time with gstreamer/v4l2sink and somehow whatsapp was the only application where the camera didn't work ("can't start camera, please restart your phone"). Thanks to the docs I tried ffmpeg and the avd camera worked immediately. Maybe the camera resolution was wrong idk (I used ipcam/my phone's camera/tried some wierd hand written screen resolutions/cut the image with imagemagick's convert)
