### ISSUE TITLE
Does not build on Debian Buster

### ISSUE THREAD

**Issue by Nothing4You** [tulir/mautrix-whatsapp#112]
Hi,

I'm not really familiar with go but it does not seem to build currently:
```
$ go build
# maunium.net/go/mautrix-whatsapp
./portal.go:1180:31: undefined: strings.ReplaceAll
$ echo $?
2
```
No binary seems to be generated

**Comment by Nothing4You** [comment]
The affected line was added in 03d42640fe67a7262d160497cd79678612249cc5

**Comment by Nothing4You** [comment]
After some googling it seems like ReplaceAll was only added in go 1.12 while debian buster only ships go 1.11. what are your plans regarding supporting older go versions?

**Comment by Nothing4You** [comment]
Unfortunately I can't seem to find a way to use this at the moment.

Build on macOS: fails due to https://github.com/chai2010/webp failing to build
Build on Debian: fails due to older golang version
Build on Arch Linux: works, can't use binary on Debian due to older libc
Build on Arch Linux with CGO_ENABLED=0: fails due to https://github.com/chai2010/webp failing to build

**Comment by tulir** [comment]
You can just download a build from the [CI](https://mau.dev/tulir/mautrix-whatsapp/pipelines) or download a newer version of [Go](https://golang.org/dl/)

**Comment by Nothing4You** [comment]
Built with a tgz download from golang.org, works now.
