### ISSUE TITLE
Failed to start bridge with postgresql

### ISSUE THREAD

**Issue by Pcornat** [tulir/mautrix-whatsapp#117]
Hello again,

Here is the problem : I start the bridge with the synapse user (the same as the synapse server), then I get this error :
`[Dec  1, 2019 22:17:07] [FATAL] Failed to initialize database: parse postgresql://synapse:xG8dda!/ 'rest of the DB password' @localhost/synapse: invalid port ":xG8dda!" after host`

I do not have any other thing to help you, sorry.

**Comment by Pcornat** [comment]
OK, I changed the password to remove the `/` character. It works, except that I have the following problem : `[FATAL] Failed to initialize database: pq: SSL is not enabled on the server`. I will solve it myself.

**Comment by Pcornat** [comment]
I solved it, and now I have this problem : `[FATAL] Failed to initialize database: pq: the constraint " message_chat_jid_fkey" from relation "message" doesn't exist`. That's all.

**Comment by tulir** [comment]
Are you trying to reuse the same database for many things?

**Comment by Pcornat** [comment]
Well this database, called synapse, is my matrix homeserver's database

**Comment by pwr22** [comment]
I have the same issue even when pointing at another database

**Comment by tulir** [comment]
Reusing the same database for many bridges isn't supported. There might be other unrelated bugs, but those need a separate issue.

**Comment by Cogitri** [comment]
It appears that this happened for me in a clean database. It appears that the upgrades fail on clean Postgres12 DBs due to https://github.com/tulir/mautrix-whatsapp/blob/master/database/upgrades/2019-05-16-message-delete-cascade.go#L13. After commenting that line out everything works as expected.
