### ISSUE TITLE
User details (display name, profile picture) are not set correctly until restarting the bridge

### ISSUE THREAD

**Issue by Nothing4You** [tulir/mautrix-whatsapp#121]
~14:50: user is added to the WA group
14:53: someone sends a message which is bridged successfully
14:53: i'm running sync in the control room (see #120)
> WhatsApp bridge bot invited whatsapp_49xxxxxxxxx.
> whatsapp_49xxxxxxxxx joined the room.

15:07: i'm restarting the bridge
> whatsapp_49xxxxxxxxx changed their display name to +49xxxxxxxxx (WA).
> +49xxxxxxxxx (WA) set a profile picture.

**Comment by markusschweitzer** [comment]
I'm having the same issue

**Comment by tulir** [comment]
This might work better on the master branch now
