### ISSUE TITLE
Messages sent in whatsapp are not correctly puppeted with login-matrix

### ISSUE THREAD

**Issue by Nothing4You** [tulir/mautrix-whatsapp#125]
![image](https://user-images.githubusercontent.com/3694534/71162842-375e3080-224c-11ea-9467-532192db2ef8.png)

This is a normal 1:1 conversation in whatsapp.
First message was sent by the conversation partner, second one was sent in whatsapp.

The bridge temporarily adds the non-puppeted user to the chat and removes it after the message was delivered.

I was only able to reproduce this when starting the bridge for now due to #124.

**Comment by tulir** [comment]
Backfilling history uses the default puppet intentionally to avoid rate limits
