### ISSUE TITLE
Failed to make puppet of ... unexpected end of JSON input

### ISSUE THREAD

**Issue by wapsi** [tulir/mautrix-whatsapp#128]
Replacing WhatsApp account's Matrix puppet with Matrix account does work only with couple of my WhatsApp groups.

Almost all of my groups are failing with this error message:
```
[Matrix/@<mynick>:matrix/DEBUG] POST http://127.0.0.1:8008/_matrix/client/r0/register {"username":"<mynick>","initial_device_display_name":""}
[Portal/3581234567-xxxxx@g.us/WARN] Failed to make puppet of 3581234567@s.whatsapp.net join !xxx:matrix: unexpected end of JSON input
```
mautrix-whatsapp: 2019-12-06 (the latest binary from the pipelines)

matrix-synapse version:
ii  matrix-synapse                1.7.2-1~bpo10+1             all          Matrix reference homeserver

**Comment by wapsi** [comment]
I just discovered that at the matrix-synapse logs there are this kind of events whenever mautrix-whatsapp tries to take over the puppet:
`synapse.api.auth: [POST-1349] Unrecognised appservice access token.`

But I think the appservice access token should be OK because all other functionalities of mautrix-whatsapp are working properly and even the puppet replacing works for couple of my WA rooms, not for all (the as_token & hs_token are the same in the config.yaml and in the registration.yaml and matrix-synapse is pointing to the correct registration.yaml file)?

**Comment by tulir** [comment]
The fix might require a re-login (`logout-matrix` and then log in again)

**Comment by wapsi** [comment]
Thanks, I tried this but looks like it isn't working. I'm still getting user who has my phone number in the WA groups. And now it's re-sending all messages that are sent from my phone (from the real WhatsApp) so all my messages are shown two times?
