### ISSUE TITLE
Postgres 12 breaks database foreign key upgrade

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-whatsapp#133]
The foreign key naming scheme changed, so https://github.com/tulir/mautrix-whatsapp/blob/master/database/upgrades/2019-05-16-message-delete-cascade.go#L13 doesn't work with a fresh database

**Comment by kravietz** [comment]
Also getting this when trying to run the bridge for the first time on PostgreSQL 12.

**Comment by killua-eu** [comment]
I'd love to bump pg to version 12, any progress on this one?
