### ISSUE TITLE
Error when restarting matrix-synapse

### ISSUE THREAD

**Issue by Nthl25** [tulir/mautrix-whatsapp#136]
Hi, 
I followed the instructions from the wiki but if I restart matrix-synapse I get the error message "Required string field: 'id'".

`Jan 15 17:39:13 matrix matrix-synapse[10192]: 2020-01-15 17:39:13,082 - twisted - 192 - ERROR -  - KeyError: "Required string field: 'id' (<path>/mautrix-whatsapp/config.yaml)"

Jan 15 17:39:13 matrix systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE

Jan 15 17:39:13 matrix systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.

Jan 15 17:39:16 matrix systemd[1]: matrix-synapse.service: Service hold-off time over, scheduling restart.

Jan 15 17:39:16 matrix systemd[1]: matrix-synapse.service: Scheduled restart job, restart counter is at 5.
`

Does anyone know what the problem is?
If I take a look at the config.yaml I can find a row with the content "id: whatsapp".
But I can not find any information about this...

**Comment by rreuvekamp** [comment]
Normally Synapse shouldn't have to access the config of the bridge. Synapse needs to have the registration file which the bridge generates for you. Is it possible you mixed them up?

**Comment by Nthl25** [comment]
Yes, you are right. I mixed them up.
But if I change the file I get the information that I do not have the permissions to the registrations file:

 PermissionError: [Errno 13] Permission denied: '/etc/mautrix-whatsapp/registration.yaml'

I've tried to run it as root, changed the permissions but nothing fixed this issue. Any ideas how to solve that?
