### ISSUE TITLE
messages appear twice if sent from whatsapp

### ISSUE THREAD

**Issue by bendschs** [tulir/mautrix-whatsapp#139]
I think this has to do with the login-matrix. If i send messages from mobile via whatsapp they appear twice in whatsapp (and only once in riot). In rare cases it even creates a infinite loop of messages being sent tlil i stop and restart mautrix-whatsapp.

is something wrong with my login-matrix?

cheers
bendsch

**Comment by tulir** [comment]
#132?

**Comment by bendschs** [comment]
seems to be this one .. yes! so is it solved in the most recent version?

**Comment by bendschs** [comment]
seems to work now ... 
just one question: why is there  any release-tracking for this repository?
