### ISSUE TITLE
Failed to join room

### ISSUE THREAD

**Issue by Nthl25** [tulir/mautrix-whatsapp#143]
Hi@all,

I've set up my matrix bride but if I invide the bot into my room I get the following log:

[Feb 15, 2020 16:02:52] [Matrix/DEBUG] Failed to join room !cqfKLd[..] with invite from [...].

Do you have any ideas how I can solve that?

**Comment by progserega** [comment]
May be you need enable `allow_user_invite: true` options in mautrix-whatsapp bridge config?

**Comment by Nthl25** [comment]
allow_user_invite is set to "true" but I still get this error message (I copied the default config to my config.yaml file, changed the settings and used "./mautrix-whatsapp -g" again).
Did I forget something?

**Comment by tulir** [comment]
That option isn't related to the error. Looks like the main problem is that the log message doesn't actually print the error ([here](https://github.com/tulir/mautrix-whatsapp/blob/master/matrix.go#L66))
