### ISSUE TITLE
community_template: Actually, how does this work? (Confusing documentation)

### ISSUE THREAD

**Issue by IngwiePhoenix** [tulir/mautrix-whatsapp#153]
I am trying to group my bridges into communities to easier oversee various groups and direct messages that I am involved in. Fortunately, this doesn't seem too difficult. I mean it works for IRC and Telegram. But how does it work for Whatsapp?

The documentation given to `community_template` doesn't exactly explain if this will *create a new community on the server* or if this is something else. Plus the format seems off, as normally, communities are `+communityName:domain` - but in the given setting, it could equal to `whatsapp_baz=foo.bar` - which is incorrect.

So how can I have portals to direct messages and groups be organized properly? Thanks!

**Comment by tulir** [comment]
It creates a new community for every user. What do you mean incorrect?

**Comment by tulir** [comment]
Comment improved by #138
