### ISSUE TITLE
into Go value of type map[string]interface {}

### ISSUE THREAD

**Issue by DoM1niC** [tulir/mautrix-whatsapp#156]
for some Minutes I got this Error :( 

```
Unknown error while reconnecting: error decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {}

Your WhatsApp connection was closed with websocket status code 1000. Use the reconnect command to reconnect.
```

**Comment by olmari** [comment]
Error became to world few hours ago, and it is already fixed on master, so `git pull` and `go build` as per wiki or update docker image if got one, and enjoy working bridge again :)

**Comment by DoM1niC** [comment]
ok I have to try I already pulled the current Code without success give me a sec

**Comment by DoM1niC** [comment]
yeah I see the WA Bridge is written in Go and have to recompile, TXH anyway
