### ISSUE TITLE
Not able to log into whatsapp

### ISSUE THREAD

**Issue by Niun92** [tulir/mautrix-whatsapp#159]
Hi, there is a Problem since today (26.03.20):
The Bridge disconnectet with error:

`Unknown error while logging in: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}
Your WhatsApp connection was closed with websocket status code 1000. Use the reconnect command to reconnect.`

Deleting the session and relog causes the same error.

I´ve pulled the last version, WHatsApp is running on an old tablet.
Debug log:

`
[Mar 26, 2020 23:45:49] [User/@!!!!!!/DEBUG] Connecting to WhatsApp
[Mar 26, 2020 23:45:49] [User/@!!!!!!/DEBUG] WhatsApp connection successful
[Mar 26, 2020 23:45:50] [User/@!!!!!!/WARN] Failed to log in: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}

[Mar 26, 2020 23:45:50] [User/@!!!!!!/ERROR] WhatsApp error: server closed connection,code: 1000,text: 
[Mar 26, 2020 23:52:44] [INFO] Interrupt received, stopping...
[Mar 26, 2020 23:52:44] [DEBUG] Disconnecting @!!!!
[Mar 26, 2020 23:52:44] [Matrix/DEBUG] Listener stopped.
[Mar 26, 2020 23:52:44] [ERROR] Error while disconnecting @!!!!: not connected
`

**Comment by olmari** [comment]
Fixed already, see https://github.com/tulir/mautrix-whatsapp/issues/156

**Comment by Niun92** [comment]
Thanks.
It was my fault, forgot to compile it.
