### ISSUE TITLE
Mark messages read on Matrix side as read on WhatsApp

### ISSUE THREAD

**Issue by PureTryOut** [tulir/mautrix-whatsapp#16]
Title. Currently this doesn't happen, making it unclear which messages you have or have not read if using WhatsApp directly on your phone.

**Comment by krombel** [comment]
blocked my [MSC1145](https://github.com/matrix-org/matrix-doc/issues/1145)

**Comment by tulir** [comment]
Matrix puppeting like the Telegram bridge is planned

**Comment by tulir** [comment]
This was added some time back, works with `login-matrix <access token>`
