### ISSUE TITLE
bridge no longer able to connect to whatsapp

### ISSUE THREAD

**Issue by performantp** [tulir/mautrix-whatsapp#160]
Since March 26th 2020 17:15 (that's what my whatsapp web is saying) the bridge can no longer connect to whatsapp.
The following errormessage is displayed when trying to send the `reconnect` command to the bot:
`Unknown error while reconnecting: error decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {}`
`Your WhatsApp connection was closed with websocket status code 1000. Use the reconnect command to reconnect.`
This is quite severe, as it makes the bridge basically unusable

**Comment by julianuu** [comment]
Experiencing the same. Since March 26 20:02 UTC.

**Comment by julianuu** [comment]
ok updating the bridge fixed it
