### ISSUE TITLE
Images sent from matrix aren't forwarded to whatsapp

### ISSUE THREAD

**Issue by lhaus** [tulir/mautrix-whatsapp#161]
Log says:
`mautrix-whatsapp[1011641]: [Apr  2, 2020 01:54:17] [Portal/4369918172056@s.whatsapp.net-436606254787@s.whatsapp.net/ERROR] Failed to upload media in $FTwqNV0BcFtx0fCpPE01Qbw5yKzaiby_G8dz-RkCaW8: upload responsed with 404`

**Comment by tulir** [comment]
Update your bridge

**Comment by lhaus** [comment]
thanks, working now. I really should remember to do that before opening issues from now on :)
