### ISSUE TITLE
Option to disable status updates

### ISSUE THREAD

**Issue by PureTryOut** [tulir/mautrix-whatsapp#166]
I'd like an option to disable/remove the "WhatsApp Status Broadcast" thing. I'm not interested in that functionality and even if I did, I'd like it in some more integrated format than having it as just another room.

I don't mind if it's either a bridge-wide setting or a per-user setting.

**Comment by Eskuero** [comment]
I'm also in for this. There's some noisy people who constantly put stories and in general I'm not insterested in any so I'd like to completely stop it from happening.

**Comment by rharkes** [comment]
Would indeed be great if this was an option. Especially around christmas-time it seems many people don't know they broadcast these status things to the entire contactlist.

**Comment by csett86** [comment]
There is a workaround available to disable the status updates globally if you use iOS for the WhatsApp app: Disable access to the address book for WhatsApp, then WhatsApp decides that you no longer should be able to receive status updates. Yes, you then also dont see contact names in your chat history, so it comes with its own drawback. But you can still send an receive messages and start new conversations with others (via their phone number).

**Comment by knoedel001** [comment]
Hello,

I'm using the whatsapp-bridge in a docker-container with a config file created by https://github.com/spantaleev/matrix-docker-ansible-deploy. Adding _enable_status_broadcast: false_ to the bridge-section of config.yaml did not disable the status updates. Can you please give me advice on how to investigate the issue? Container dock.mau.dev/mautrix/whatsapp is on the latest version from 16h ago.

[config.yaml.txt](https://github.com/mautrix/whatsapp/files/7153428/config.yaml.txt)

**Comment by etkecc** [comment]
The issue still exists (both with v0.30 and the latest / master)

Please, reopen it

**Comment by Eskuero** [comment]
I honestly have had enabled since the config was added and it works. Running 0.3.0 right now since it was releases. If you delete the broadcast channel does it get re-added when a new story comes through?

**Comment by etkecc** [comment]
yes. After applying of the config var, a new matrix user was created and logged in into the bridge, so any puppets related to that new matrix user should not have broadcasts, but apparently they have
