### ISSUE TITLE
Whatsapp just updated something?

### ISSUE THREAD

**Issue by davralin** [tulir/mautrix-whatsapp#169]
Several users in ```#whatsapp:maunium.net``` had faulty whatsapp-connections at the same time.

Here are the relevant logs from my running container:

```
[Apr 21, 2020 01:35:28] [User/@user:homeserver.com	/ERROR] WhatsApp error: connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF
[Apr 21, 2020 01:35:29] [Puppet/1234567890@s.whatsapp.net/DEBUG] Skipping sync processing: custom user not connected to whatsapp
[Apr 21, 2020 01:35:29] [Matrix/@user:homeserver.com/DEBUG] GET https://homeserver.com/_matrix/client/r0/sync?filter=3&set_presence=offline&since=s154306_2830202_2001_122947_458_28_5_17964_1&timeout=30000
[Apr 21, 2020 01:35:39] [Puppet/1234567890@s.whatsapp.net/DEBUG] Skipping sync processing: custom user not connected to whatsapp
[Apr 21, 2020 01:35:39] [Matrix/@user:homeserver.com/DEBUG] GET https://homeserver.com/_matrix/client/r0/sync?filter=3&set_presence=offline&since=s154306_2830232_2001_122947_458_28_5_17964_1&timeout=30000
[Apr 21, 2020 01:35:40] [Puppet/1234567890@s.whatsapp.net/DEBUG] Skipping sync processing: custom user not connected to whatsapp
[Apr 21, 2020 01:35:40] [Matrix/@user:homeserver.com/DEBUG] GET https://homeserver.com/_matrix/client/r0/sync?filter=3&set_presence=offline&since=s154306_2830232_2001_122948_459_28_5_17964_1&timeout=30000
[Apr 21, 2020 01:35:48] [User/@user:homeserver.com/ERROR] Error while trying to reconnect after disconnection: restore session init timed out
[Apr 21, 2020 01:35:48] [User/@user:homeserver.com/ERROR] WhatsApp error: keepAlive failed: connection timed out
[Apr 21, 2020 01:35:48] [User/@user:homeserver.com/ERROR] WhatsApp error: server closed connection,code: 1000,text: 
[Apr 21, 2020 01:35:52] [User/@user:homeserver.com/ERROR] Error while trying to reconnect after disconnection: login or restore already running
[Apr 21, 2020 01:36:00] [User/@user:homeserver.com/ERROR] Error while trying to reconnect after disconnection: login or restore already running
[Apr 21, 2020 01:36:09] [User/@user:homeserver.com/ERROR] Error while trying to reconnect after disconnection: restore session init timed out
[Apr 21, 2020 01:36:09] [User/@user:homeserver.com/ERROR] WhatsApp error: keepAlive failed: connection timed out
[Apr 21, 2020 01:36:09] [User/@user:homeserver.com/ERROR] WhatsApp error: server closed connection,code: 1000,text: 
[Apr 21, 2020 01:36:10] [Puppet/1234567890@s.whatsapp.net/DEBUG] Skipping sync processing: custom user not connected to whatsapp
[Apr 21, 2020 01:36:10] [Matrix/@user:homeserver.com/DEBUG] GET https://homeserver.com/_matrix/client/r0/sync?filter=3&set_presence=offline&since=s154310_2830246_2001_122949_460_28_5_17964_1&timeout=30000
[Apr 21, 2020 01:36:10] [Puppet/1234567890@s.whatsapp.net/DEBUG] Skipping sync processing: custom user not connected to whatsapp
```

**Comment by pidongqianqian** [comment]
I got a similar error：
```
[Apr 21, 2020 10:32:55] [User/@pidong_local:oliver.matrix.host/DEBUG] Connecting to WhatsApp
[Apr 21, 2020 10:32:57] [User/@pidong_local:oliver.matrix.host/DEBUG] WhatsApp connection successful
[Apr 21, 2020 10:32:57] [User/@pidong_local:oliver.matrix.host/ERROR] WhatsApp error: server closed connection,code: 1000,text: 
```

**Comment by christianlupus** [comment]
Can confirm this as well. New logins are not possible either.

**Comment by jdfranel** [comment]
Same problem here

`
[Command handler/DEBUG] @user:server.tld sent 'reconnect' in !ABCDEFGHIJKLMNOPQR:server.tld
[Apr 21, 2020 06:39:16] [User/@user:server.tld/DEBUG] Got invalid session error when reconnecting, but user has session. Retrying using RestoreWithSession()...
[Apr 21, 2020 06:39:36] [User/@user:server.tld/WARN] Error while reconnecting: restore session init timed out
[Apr 21, 2020 06:39:36] [User/@user:server.tld/ERROR] WhatsApp error: keepAlive failed: connection timed out
[Apr 21, 2020 06:39:36] [User/@user:server.tld/ERROR] WhatsApp error: server closed connection,code: 1000,text:
[Apr 21, 2020 06:39:36] [User/@user:server.tld/ERROR] Failed to disconnect after failed session restore in reconnect command: not connected
[Apr 21, 2020 06:39:36] [User/@user:server.tld/DEBUG] Disconnecting due to failed session restore in reconnect command...
`

**Comment by pidongqianqian** [comment]
> Same problem here
> 
> ```
> [Command handler/DEBUG] @user:server.tld sent 'reconnect' in !ABCDEFGHIJKLMNOPQR:server.tld
> [Apr 21, 2020 06:39:16] [User/@user:server.tld/DEBUG] Got invalid session error when reconnecting, but user has session. Retrying using RestoreWithSession()...
> [Apr 21, 2020 06:39:36] [User/@user:server.tld/WARN] Error while reconnecting: restore session init timed out
> [Apr 21, 2020 06:39:36] [User/@user:server.tld/ERROR] WhatsApp error: keepAlive failed: connection timed out
> [Apr 21, 2020 06:39:36] [User/@user:server.tld/ERROR] WhatsApp error: server closed connection,code: 1000,text:
> [Apr 21, 2020 06:39:36] [User/@user:server.tld/ERROR] Failed to disconnect after failed session restore in reconnect command: not connected
> [Apr 21, 2020 06:39:36] [User/@user:server.tld/DEBUG] Disconnecting due to failed session restore in reconnect command...
> ```
I connected normally after 'git pull'

**Comment by jdfranel** [comment]
Everything is OK, I pulled the latest docker image and have been able to reconnect without having to rescan a new code.
