### ISSUE TITLE
video thumbnails are only 100px wide

### ISSUE THREAD

**Issue by lub** [tulir/mautrix-whatsapp#170]
That makes it very hard to display the video controls in some clients (e.g. riot-web)

I'd suggest to retain the video's resolution for the thumbnail, to prevent resizing the video player as soon as the video start playing for clients that play videos inline.
Alternatively there could be some >100px maximum width limit (e.g. 800px), to keep thumbnail size down.

Doesn't make a difference if the original is a gif or a proper video, but I suspect whatsapp encodes gifs in some video codec anyway.

**Comment by lub** [comment]
Now that I think about it the client probably should scale the thumbnail to an appropriate size to properly display all player elements, but for quality it would still be great to have more than 100px :)

**Comment by tulir** [comment]
Looks like I fixed this in 7c799f1faa2e99df3ea14663dc0173021d5eb44a (by disabling the thumbnail by default)
