### ISSUE TITLE
Synchronizing Read/Unread Status Between Matrix and Whatsapp

### ISSUE THREAD

**Issue by mdanny82** [tulir/mautrix-whatsapp#171]
It would be nice if i only have to read the message once and on both sides the read/unread status would be updated.

**Comment by lordievader** [comment]
The bridge can already do this if you replace the puppet with your own Matrix user.

**Comment by mdanny82** [comment]
ive done this already... but still not working. Had relaybot activated. After deactivation of relaybot still not working.

**Comment by lordievader** [comment]
I don't use the relaybot. Perhaps with the relaybot this works differently?

**Comment by mdanny82** [comment]
seems that relaybot was the problem. now it is working.
