### ISSUE TITLE
"Your WhatsApp connection failed" spam

### ISSUE THREAD

**Issue by anoadragon453** [tulir/mautrix-whatsapp#173]
![image](https://user-images.githubusercontent.com/1342360/80700359-7a22f580-8ad5-11ea-9a67-54f28878c19b.png)

So this pops up decently often and highlights the bridge room for me. I click it, and it's this message again.

The error and the recovery is sent one after another with 1s in between. Perhaps the bridge could wait a couple seconds and if the bridge recovers it doesn't need to send the error message?

I see how it could be useful for debugging, but one could use bridge logs instead for that.

**Comment by tulir** [comment]
https://github.com/tulir/mautrix-whatsapp/blob/master/example-config.yaml#L98-L100 has been a thing for some time now
