### ISSUE TITLE
Allow option to reconnect without emitting "Reconnected successfully" message

### ISSUE THREAD

**Issue by lingnand** [tulir/mautrix-whatsapp#177]
The Whatsapp bot seems to need to reconnect every now and then, which is fine - what gets a bit annoying is that one has to choose between a) default notification settings, which doesn't prompt for bot's messages; in this case one needs to check the bot every now and then for its new messages b) notification setting to prompt for bot messages - in this case one doesn't miss actually problematic disconnects, but a lot of extra noise such as 'trying to reconnect' and 'reconnected successfully".

I opted for b), and used the useful setting to disable 'trying to reconnect' message - but there is still the 'reconnected successfully' message that gets a bit annoying over time. Ideally I'd like to only receive messages if it needs any action from me i.e., reconnect attempts have failed. And I think that would be a saner setup for both a) and b).

**Comment by olmari** [comment]
Indeed, I can only assume occasional data connection reset is just normal occurrence in the interwebs. I'd propose that on many reconnection messages bridge would just be silent if reconnection works, if it actually fails _then_ yell the error out...

**Comment by tulir** [comment]
https://github.com/tulir/mautrix-whatsapp/blob/v0.1.1/example-config.yaml#L92-L94
