### ISSUE TITLE
Add matrix users & bots to Whatsapp-Chats

### ISSUE THREAD

**Issue by a000a** [tulir/mautrix-whatsapp#179]
It would be great to have to possibility to add matrix users & bots to whatsapp chats ands groups., so both can use bots e.g.

**Comment by olmari** [comment]
Best ther ecan exist is relaybot. Whatsapp does not support any kind of user puppeting, nor it even really support any 3rd-party clients etc.

**Comment by a000a** [comment]
there is no need for any enhancement on the whatsapp side, i think.
just let matrix-users add other users to a whatsapp-groups, that can read and send messages in the name of the bridge

**Comment by olmari** [comment]
So.. relay bot feature, which exist already https://github.com/tulir/mautrix-whatsapp/wiki/Relaybot
