### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by derritter88** [tulir/mautrix-whatsapp#180]
Hi there,

I downloaded the latest compiled binary and installed the bridge according to the manual.
Unfortunately I am not able to start the bridge as I get following error when trying to start the bridge via `./mautrix-whatsapp`

I tried to run this command as my matrix user as well as root.

The output on screen says: 
[May 13, 2020 20:47:24] [DEBUG] Initializing database
[May 13, 2020 20:47:24] [DEBUG] Initializing state store
[May 13, 2020 20:47:24] [DEBUG] Initializing Matrix event processor
[May 13, 2020 20:47:24] [DEBUG] Initializing Matrix event handler
[May 13, 2020 20:47:24] [WARN] Bridge built without end-to-bridge encryption, but encryption is enabled in config
[May 13, 2020 20:47:24] [DEBUG] Bridge built without end-to-bridge encryption
[May 13, 2020 20:47:24] [INFO] Bridge initialization complete, starting...
[May 13, 2020 20:47:24] [Database/Upgrade/INFO] Database currently on v15, latest: v15
[May 13, 2020 20:47:24] [DEBUG] Checking connection to homeserver
[May 13, 2020 20:47:24] [DEBUG] Starting application service HTTP server
[May 13, 2020 20:47:24] [DEBUG] Starting event processor
[May 13, 2020 20:47:24] [Matrix/INFO] Listening on 0.0.0.0:29318
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x969b10]

**Comment by sj64** [comment]
I have this issue too:

[May 21, 2020 10:56:12] [DEBUG] Initializing database
[May 21, 2020 10:56:12] [DEBUG] Initializing state store
[May 21, 2020 10:56:12] [DEBUG] Initializing Matrix event processor
[May 21, 2020 10:56:12] [DEBUG] Initializing Matrix event handler
[May 21, 2020 10:56:12] [WARN] Bridge built without end-to-bridge encryption, but encryption is enabled in config
[May 21, 2020 10:56:12] [DEBUG] Bridge built without end-to-bridge encryption
[May 21, 2020 10:56:12] [INFO] Bridge initialization complete, starting...
[May 21, 2020 10:56:12] [Database/Upgrade/INFO] Database currently on v15, latest: v15
[May 21, 2020 10:56:12] [DEBUG] Checking connection to homeserver
[May 21, 2020 10:56:12] [DEBUG] Starting application service HTTP server
[May 21, 2020 10:56:12] [DEBUG] Starting event processor
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x969be0]

goroutine 1 [running]:
main.(*Bridge).Start(0xc0000cab60)	/builds/tulir/mautrix-whatsapp/main.go:257 +0x290
main.(*Bridge).Main(0xc0000cab60)	/builds/tulir/mautrix-whatsapp/main.go:350 +0xcc
main.main()	/builds/tulir/mautrix-whatsapp/main.go:377 +0x105

**Comment by sj64** [comment]
PS
Latest static binary
minimal config
Ubuntu 20.04

**Comment by tulir** [comment]
Open a new issue **with the full stack trace** if it still happens.
