### ISSUE TITLE
Failed to restore session

### ISSUE THREAD

**Issue by abdullasharapov** [tulir/mautrix-whatsapp#184]
The bridge is running in the container. Everything worked great for several days, but today I needed to restart the server. After that, the bot refuses to connect to the session.
Log
`Failed to restore session: admin login errored: 401 (unpaired from phone)
[User/@xxx:example.com/DEBUG] Disconnecting due to failed session restore...`
but the web session on the phone is not stopped. How to restore a session? Whatsapp is running in the emulator, every time after reboot scan a QR with web-camera is a hard job)))

**Comment by tulir** [comment]
That seems like a fairly clear error, the bridge can't do anything if WhatsApp says it's unpaired.
