### ISSUE TITLE
Compilation Error 

### ISSUE THREAD

**Issue by voipsense** [tulir/mautrix-whatsapp#186]
error compilation

i used last go build "go1.14.3.linux-amd64.tar.gz"

mautrix-whatsapp]# git clone https://github.com/tulir/mautrix-whatsapp.git
 mautrix-whatsapp]# go build
# maunium.net/go/mautrix/crypto/olm
../../pkg/mod/maunium.net/go/mautrix@v0.4.5/crypto/olm/account.go:4:22: fatal error: olm/olm.h: No such file or directory
 // #include <olm/olm.h>

**Comment by tulir** [comment]
I had forgot to update the setup wiki, but it should contain all the necessary info now

**Comment by voipsense** [comment]
thankyou can you guid to find olmlib for centos 7

**Comment by tulir** [comment]
CentOS 8 EPEL seems to have it, not sure about 7. You can always build it yourself (https://gitlab.matrix.org/matrix-org/olm) or just disable encryption and sqlite.
