### ISSUE TITLE
Can't find file ./mautrix-whatsapp

### ISSUE THREAD

**Issue by Alexandero89** [tulir/mautrix-whatsapp#187]
I downloaded the precompiled binary for arm and try to start the binary with:
"./mautrix-whatsapp" 
and get following error (in german):
"zsh: datei oder Verzeichnis nicht gefunden: ./mautrix-whatsapp"
in english it is something like:
"zsh: file or location not found: ./mautrix-whatsapp"

Running the arm64 binary on a raspberry4 with buster and 64bit kernel.

If you could tell me how i could provide you some logs or anything else i would gladly help with that.

**Comment by tulir** [comment]
Did you read the instructions in [the wiki](https://github.com/tulir/mautrix-whatsapp/wiki/Bridge-setup)? (specifically the bullet points in the "Downloading a prebuilt executable" part)

**Comment by Alexandero89** [comment]
Actually yes, but repeated the instructions and found that i installed libolm2 and not libolm3 because raspbian buster has no libolm3.
My bad, sorry.

But a static binary for arm is not available (also fyi: using postgres).

Is there any solution?

**Comment by tulir** [comment]
Not sure why I had only added static builds for amd64, since cross-compiling Go without C is very trivial. https://mau.dev/tulir/mautrix-whatsapp/-/jobs/2605/artifacts/browse should work now

**Comment by Alexandero89** [comment]
Damn! 
Best responsetime and support i've seen for a very long time.

Thank you very much. Its starting now with static build.
