### ISSUE TITLE
Bridge unpuppeted matrix users as a bot user to Whatsapp

### ISSUE THREAD

**Issue by Half-Shot** [tulir/mautrix-whatsapp#20]

**Comment by tulir** [comment]
WhatsApp doesn't have actual bots (the business API is useless and limited beta). This issue is about adding an option to use one whatsapp user as a relay for users who haven't logged in.

**Comment by x-0n** [comment]
Does whatsapp do regex matching to detect bots? If not, how does their banhammer work?

**Comment by tulir** [comment]
They don't seem to ban any 3rd party clients that use the web app API, which is how the bridge works at all without being banned. Using one user as a relaybot shouldn't be any different (forgot mention this in my other message)

**Comment by homebeach** [comment]
How do they detect you are using 3rd party client?

**Comment by vmario89** [comment]
id like to be able to make a special whatsapp group available to users in matrix, who do not own a whatsapp account, to allow read content from that group (and maybe reply to that group)
