### ISSUE TITLE
Bot encryption

### ISSUE THREAD

**Issue by derritter88** [tulir/mautrix-whatsapp#200]
Is it possible to have an encrypted communication between Riot user & Whatsapp bot?

**Comment by derritter88** [comment]
Okay found encryption

**Comment by visika** [comment]
Once I enabled encryption it tells me `[WARN] End-to-bridge encryption enabled, but login_shared_secret not set`. Can I just ignore this and send encrypted messages to the bot or should I provide that value? If so, where could I find that? In Synapse's config.yaml and start log I can't find that.
