### ISSUE TITLE
Can't send login to the bot

### ISSUE THREAD

**Issue by jeena** [tulir/mautrix-whatsapp#204]
I compiled and installed according to https://github.com/tulir/mautrix-whatsapp/wiki/Bridge-setup and I invited the bot into a room and it said `This room has been registered as your bridge management/status room. Send "help" to get a list of commands.` but after that nothing happens.

The last thing in the log it says:

`[Matrix/DEBUG] !ZcPZIiFAkPewUjQflL:jeena.net registered as a management room with @jeena:jeena.net`

I write "help" and "login" which shows up in Riot but nothing happens after that. I restarted it and the log only says:

```
DEBUG] Initializing database
[DEBUG] Initializing state store
[DEBUG] Initializing Matrix event processor
[DEBUG] Initializing Matrix event handler
[DEBUG] Bridge built with end-to-bridge encryption, but disabled in config
[INFO] Bridge initialization complete, starting...
[Database/Upgrade/INFO] Database currently on v15, latest: v15
[DEBUG] Checking connection to homeserver
[DEBUG] Starting application service HTTP server
[DEBUG] Starting event processor
[INFO] Bridge started!
[Matrix/INFO] Listening on jeena.net:29318
[DEBUG] Updating bot profile
[DEBUG] Starting users
[DEBUG] Starting custom puppets
```

**Comment by jeena** [comment]
It might have been that I by mistake made the room encrypted and then the bot didn't understand what I wanted from them. I kicked the bot out and left the room. Then I created a new room which was not encrypted and invited the bot in there. Sadly it didn't show the `This room has been registered as your bridge management/status room. Send "help" to get a list of commands.` in this new room and riot shows me that the bot has been offline for 12 days. Not sure how I can bring it back online.

I did an update and rebuild it, then I restarted the bridge and the server but nothing shows up, the log is as it was before, stopps with "Starting custom puppets".

**Comment by jeena** [comment]
That seemed to have been the problem I reset and created a new room etc and now it works.

**Comment by visika** [comment]
Thanks for the info. I managed to make it work by deleting `mautrix-whatsapp.db` and then inviting the bot to an unencrypted room.

**Comment by gabrix73** [comment]
Apparently the matriux-whatsapp.db file is not present on my system. 

[https://ibb.co/j37NGgY]

What exactly are you referring to? 

I left the whatsapp bot room and in the next search I always have an encrypted room that doesn’t respond to commands. 
The whatsapp bot is offline.
