### ISSUE TITLE
Nicknames in group chats are given by the bot

### ISSUE THREAD

**Issue by christianlupus** [tulir/mautrix-whatsapp#206]
I have the problem that I am a participant in multiple groups. Some of the other users have set an alias in Whatsapp. These chat rooms are represented as matrix rooms (good!) and the name of the persons (puppets) are taken from the bridge.
The bridge seems to prefer the alias over the name of the contact within my address book. As a result, I cannot identify these people manually.

In 1:1 chats I can rename the chat room according to the user's name manually. But in group chats, this is not possible.
The bad side is that I have a few jesters in such groups that just put an emoji in their alias rendering them almost impossible to identify.

The best way (from my perspective) would be if I could set the names of the contacts either according to the name in the address book of the phone or manually in the matrix bridge.

**Comment by tulir** [comment]
Users are named according to the [configuration](https://github.com/tulir/mautrix-whatsapp/blob/master/example-config.yaml#L68-L76). It defaults to using the remote user-set name to prevent conflicts in multi-user bridge instances.
