### ISSUE TITLE
Error connecting to homeserver

### ISSUE THREAD

**Issue by SySx-Dragonfire** [tulir/mautrix-whatsapp#212]
Hi, 
By running the matrix bridge either by self compiling or with docker i get this error message:     
[ERROR] Failed to connect to homeserver: failed to ensure registered: msg=Failed to POST JSON to /_matrix/client/r0/register:  code=502 wrapped=. Retrying in 10 seconds...
What does this mean?    
Maybe I have to open some ports or do I have to make some optimizations on my nginx?

Thanks

**Comment by tulir** [comment]
The server you set in `homeserver`→`address` is responding with HTTP 502 (bad gateway).
