### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by MelBourbon** [tulir/mautrix-whatsapp#213]
I followed the instructions in the wiki to set up the bridge with docker on my current matrix server. But restarting the server with the line `app_service_config_files:` added to `homeserver.yaml` does not work. I receive the following error message:

```
 PermissionError: [Errno 13] Permission denied: '/var/www/mautrix-whatsapp/registration.yaml'
```

**Comment by Legogris** [comment]
Have you checked that:
* The file is exists at that location in the synapse container? (The registration file should be for synapse, not for the bridge)?
* the user running synapse has permissions to that file?

sanity checks if you're not that familiar is just to (with your existing configuration for the container) fo a `docker run --rm -it [...] sh` and:

```
$ whoami # get current user
$ ls -la /var/www/mautrix-whatsapp/
```

**Comment by HayWo** [comment]
The error means that the linux-user which runs the homeserver has no reading permissinos on the file `registration.yaml`.
There are multiple ways to solve this:

- Change the permissions of the registration file using this command:
   ```
   chmod 644 registration.yaml
   ```
    This means anyone can read the file and only the owner can write to it.

- Change the owner of the file to the linux-user of the homeserver by running:
   ```
   chown username registration.yaml
   ```
   This might cause a permission denied error when you need to recreate the registration file.

- Change the group that file belongs to to a group that the homeserver user is part of by using: 
   ```
   chgrp groupname registration.yaml
   ```
    And give the group read perrmissions with:
   ```
   chmod 640 registration.yaml
   ```

The first solution is propably the easiest, the last one is a bit more secure.

All of these solutions definetly work for non docker setups, so there might be extra steps to do when using docker (I have no experience with that).

**Comment by MelBourbon** [comment]
@HayWo I willl try the solutions and reply. One problem I see is that the docker is always changing the owner of the data folder to UID 1337 as described in the wiki. That's the reason why I never tried the options you suggested as I wonder why I'm the first running into this issue. And I guess option 2/3 will only work until I update the docker and I need to change afterwards again.

**Comment by Legogris** [comment]
you also have env vars `UID` and `GID` for the container if you want to change it from 1337 to another user/group.

**Comment by MelBourbon** [comment]
@Legogris Can I set these in `docker-compose.yml`?

**Comment by Legogris** [comment]
@MelBourbon Yes. But if you're hapy having them set at `1337:1337` the no need to!

**Comment by MelBourbon** [comment]
Ok, I will close the issue for now as this problem is fixed and I now run into the next one 👍
