### ISSUE TITLE
Suppress "has changed their profile picture" messages in every channel the contact is in?

### ISSUE THREAD

**Issue by myxor** [tulir/mautrix-whatsapp#215]
Is it possible to suppress the "has changed their profile picture" messages in every channel the contact is in?

If not this would be a good new feature.

**Comment by tulir** [comment]
If you mean the user changed their avatar on WhatsApp, no, the bridge is working correctly. You can ask your client to hide avatar changes.

If you mean that the user already had an avatar on Matrix and didn't change it on WhatsApp, provide more details (e.g. is it consistently reproducible and if yes, how to reproduce it)
