### ISSUE TITLE
Failed to connect to homeserver: msg=Failed to GET JSON

### ISSUE THREAD

**Issue by univdet23** [tulir/mautrix-whatsapp#219]
- I followed the configuration instructions in the wiki on this page.

-I get this error when executing ./mautrix-whatsapp
   `Failed to connect to homeserver: msg=Failed to GET JSON to /_matrix/client/r0/account/whoami code=401 wrapped=M_UNKNOWN_TOKEN: Invalid macaroon passed`

- I have synapse and mautrix-whatsapp bridge on the same server (no dockers).
- my config.yaml 
  
`homeserver:

  address: http://matrix.example.com:8008
  domain: matrix.example.com
  asmux: false
appservice:
  address: http://localhost:29318
  hostname: 0.0.0.0
  port: 29318
  database:
    type: sqlite3
    uri: mautrix-whatsapp.db
    max_open_conns: 20
    max_idle_conns: 2
  provisioning:
    prefix: /_matrix/provision/v1
    shared_secret: disable
  id: whatsapp
  bot:
    username: whatsappbot
    displayname: WhatsApp bridge bot
    avatar: mxc://maunium.net/NeXNQarUbrlYBiPCpprYsRqr
  as_token: hP7tZwv2b8S10M69bP80KFRyBZmBn7PoP0GPfQ74JrixzIoZQiDvNYy7YITsjr6
  hs_token: Z7wSpKePAzRzp3bP4JV347VAYTWxne5u5aVmpvWhGmwUBHVWoWiS4R01mUbLSN2j
metrics:
  enabled: false
  listen: 127.0.0.1:29318
whatsapp:
  device_name: Mautrix-WhatsApp bridge
  short_name: mx-wa
bridge:
  username_template: whatsapp_{{.}}
  displayname_template: '{{if .Notify}}{{.Notify}}{{else}}{{.Jid}}{{end}} (WA)'
  community_template: whatsapp_{{.Localpart}}={{.Server}}
  connection_timeout: 20
  fetch_message_on_timeout: false
  delivery_receipts: false
  login_qr_regen_count: 2
  max_connection_attempts: 3
  connection_retry_delay: -1
  report_connection_retry: true
  chat_list_wait: 30
  portal_sync_wait: 600
  user_message_buffer: 1024
  portal_message_buffer: 128
  call_notices:
    start: true
    end: true
  initial_chat_sync_count: 10
  initial_history_fill_count: 20
  initial_history_disable_notifications: false
  recovery_chat_sync_count: -1
  recovery_history_backfill: true
  sync_max_chat_age: 259200
  sync_with_custom_puppets: true
  sync_direct_chat_list: false
  default_bridge_receipts: true
  default_bridge_presence: true
  login_shared_secret: ""
  invite_own_puppet_for_backfilling: true
  private_chat_portal_meta: false
  resend_bridge_info: false
  whatsapp_thumbnail: false
  allow_user_invite: false
  command_prefix: '!wa'
  encryption:
    allow: false
    default: false
    key_sharing:
      allow: false
      require_cross_signing: false
      require_verification: true
  permissions:
    '*': 5
    '@mat1:matrix.example.com': 100
    matrix.example.com: 10
  relaybot:
    enabled: false
    management: ""
    invites: []
    message_formats:
      m.audio: <b>{{ .Sender.Displayname }}</b> sent an audio file
      m.emote: '* <b>{{ .Sender.Displayname }}</b> {{ .Message }}'
      m.file: <b>{{ .Sender.Displayname }}</b> sent a file
      m.image: <b>{{ .Sender.Displayname }}</b> sent an image
      m.location: <b>{{ .Sender.Displayname }}</b> sent a location
      m.notice: '<b>{{ .Sender.Displayname }}</b>: {{ .Message }}'
      m.text: '<b>{{ .Sender.Displayname }}</b>: {{ .Message }}'
      m.video: <b>{{ .Sender.Displayname }}</b> sent a video
logging:
  directory: ./logs
  file_name_format: '{{.Date}}-{{.Index}}.log'
  file_date_format: "2006-01-02"
  file_mode: 384
  timestamp_format: Jan _2, 2006 15:04:05
  print_level: debug`

- my registration.yaml 
 
`id: whatsapp
url: http://localhost:29318
as_token: hP7tZwv2b8S10M69bP80KFRyBZmBn7PoP0GPfQ74JrixzIoZQiDvNYy7YITsjr6
hs_token: Z7wSpKePAzRzp3bP4JV347VAYTWxne5u5aVmpvWhGmwUBHVWoWiS4R01mUbLSN2j
sender_localpart: 9dezzKxbi0udAbgaDBgwWcNUyOTROQI0
rate_limited: false
namespaces:
  users:
  - regex: ^@whatsapp_[0-9]+:matrix.example.com$
    exclusive: true
  - regex: ^@whatsappbot:matrix.example.com$
    exclusive: true`

- I tried already 2 days with different configurations, but keep getting the same error. Any help is highly appreciated.

**Comment by topikuning** [comment]
it is permission problem, please check the permission of your registration.yaml

**Comment by richardwiden** [comment]
I had that exact issue when using ansible to template out the config. The quotes around the domain name got removed for some reason.  Seems to be the case for you as well looking at your config file
