### ISSUE TITLE
Whitelisted Problem

### ISSUE THREAD

**Issue by topikuning** [tulir/mautrix-whatsapp#222]
I have make sure the Synapse is working well, but when I invite the bot it keep telling me "You are not whitelisted to use this bridge."
no error in Synapse logs or the bridge logs. any suggetion?

**Comment by tulir** [comment]
The next line in the error message tells you what to do

**Comment by topikuning** [comment]
I'm so sorry because I didn't see the config detail.
but I don't see the configuration explanation in wiki, it is not there, or I'm the one not found it.
if not, how can I help to make the documentation?
