### ISSUE TITLE
pkg missing

### ISSUE THREAD

**Issue by topikuning** [tulir/mautrix-whatsapp#224]
I'm trying to build from scratch, and it is look like some file is missing from source pkg that is used
```
# maunium.net/go/mautrix/crypto/olm
../pkg/mod/maunium.net/go/mautrix@v0.7.2/crypto/olm/account.go:4:11: fatal error: olm/olm.h: No such file or directory
```

**Comment by tulir** [comment]
Dependencies are explained on the [Bridge setup](https://github.com/tulir/mautrix-whatsapp/wiki/Bridge-setup) wiki page
