### ISSUE TITLE
bridge 'only admins can send messages' to matrix

### ISSUE THREAD

**Issue by lub** [tulir/mautrix-whatsapp#228]
In WhatsApp groups there is a setting to restrict message sending to 'only admins'. It would be great when in that case the required power level for messages on the matrix side would also be set to 50, as admins have that power level anyway.

Currently you can send messages in such a bridged matrix room, but they obviously don't get bridged to WhatsApp.

**Comment by rreuvekamp** [comment]
From testing it seems the bridge does set the correct power levels when an admin changes the setting while you're in the group.
However, when a WA-group is set as 'announce' (=only admins can send messages), and you are added to the room afterwards, the bridge doesn't bridge it. (Thanks @mro95 for helping me with testing :p )

I'll see if I can make a pull request fixing this in the following days.
