### ISSUE TITLE
Voice/video calls don’t work

### ISSUE THREAD

**Issue by bialad** [tulir/mautrix-whatsapp#229]
I’m new to bridging, but successfully set up this one.

But when I try to do incoming or outgoing voice/video calls, nothing happens. Is this supposed to work? Can’t see it as a supported feature.

**Comment by HayWo** [comment]
Bridging voice/video calls is currently not supported, as whatsapp web does not support them yet.

**Comment by bialad** [comment]
Ah, that makes sense.

**Comment by gianklug** [comment]
Can this be reopened as it is supported now?
