### ISSUE TITLE
Feature: Allow for WhatsApp deleted messages to be kept in chat but struck through

### ISSUE THREAD

**Issue by AtjonTV** [tulir/mautrix-whatsapp#237]
It would be nice to have a setting that allows for messages that where deleted in WA to be kept visible in Matrix.

Most matrix clients support for HTML and Markdown styled Text, so the Bridge could maybe just update the message to wrap it in a `<del></del>` instead of deleting it?

This is a feature I was actually hoping for when installing the bridge. Sadly this doesnt seem to be supported.

**Comment by tulir** [comment]
You can modify what the bridge does [here](https://github.com/tulir/mautrix-whatsapp/blob/v0.1.4/portal.go#L1124). I probably won't add any options into the bridge itself, but a native way to view redacted events might happen eventually ([MSC2815](https://github.com/matrix-org/matrix-doc/pull/2815))
