### ISSUE TITLE
You are not invited to this room

### ISSUE THREAD

**Issue by Ulrar** [tulir/mautrix-whatsapp#240]
Hi,

I have whatsapp setup and it seems to work fine with group chats.
However when trying to talk to someone directly, I'm getting the following error : 

```

[Dec  3, 2020 17:58:20] [Matrix/ERROR] Failed to send decryption error to !SomeId:mydomain.tld: failed to ensure joined: failed to POST /_matrix/client/r0/rooms/!SomeId:mydomain.tld:/join: M_FORBIDDEN (HTTP 403): You are not invited to this room.

[Dec  3, 2020 17:58:30] [Matrix/DEBUG] Didn't get SomeOtherLongId, giving up on $AnotherLongThing

```

Not sure what's actually relevant in there, hid what looked like IDs just in case.
I am getting messages from that person, but they're not getting my replies and the above error shows in the mautrix-whatsapp logs everytime I send a message.
I've tried deleting the room in matrix and getting the bridge to re-invite me to it, no change.

I don't have a lot of whatsapp contacts so it's hard to test but I've tried another one and I got the same error, so I think it's all private conversations.

I do note that people are showing as unverified (red shield) but can't be verified as they have no sessions listed in element.

Thanks

**Comment by tulir** [comment]
Encryption requires the bridge bot to be in the room

**Comment by Ulrar** [comment]
Do you mean I need to manually invite the bot to private rooms ?

**Comment by tulir** [comment]
Yes, currently if you manually enable encryption, you also need to manually invite the bot. If the bridge enables encryption (i.e. `default: true` in the config), it'll automaticaly invite the bot

**Comment by Ulrar** [comment]
I had `allow: true` which I guess encrypts, but `default: false` so the bot didn't join and I didn't have permission to invite it.
I've changed `default: true` and restarted it, the bot automatically joined the room and it seems to be working fine now.

Thanks !
