### ISSUE TITLE
Failed to restore session: admin login errored: 419 (unknown error)

### ISSUE THREAD

**Issue by Mynacol** [tulir/mautrix-whatsapp#241]
I am running this bridge successfully for months. Thanks @tulir!
The current version is 0.1.4 - commit `1edf8bb9`

Earlier this day the bridge reported `Failed to connect to WhatsApp...`. I responded `reconnect` and the bridge answered with `Unknown error while reconnecting: admin login errored: 419 (unknown error)`.

I restarted the emulator with WhatsApp and (multiple times) the bridge. The smallest and most recent log is:
```
[Dec  7, 2020 20:42:43] [DEBUG] Initializing database
[Dec  7, 2020 20:42:43] [DEBUG] Initializing state store
[Dec  7, 2020 20:42:43] [DEBUG] Initializing Matrix event processor
[Dec  7, 2020 20:42:43] [DEBUG] Initializing Matrix event handler
[Dec  7, 2020 20:42:43] [WARN] Bridge built without end-to-bridge encryption, but encryption is enabled in config
[Dec  7, 2020 20:42:43] [DEBUG] Bridge built without end-to-bridge encryption
[Dec  7, 2020 20:42:43] [INFO] Bridge initialization complete, starting...
[Dec  7, 2020 20:42:43] [Database/Upgrade/INFO] Database currently on v19, latest: v19
[Dec  7, 2020 20:42:43] [DEBUG] Checking connection to homeserver
[Dec  7, 2020 20:42:43] [DEBUG] Starting application service HTTP server
[Dec  7, 2020 20:42:43] [DEBUG] Starting event processor
[Dec  7, 2020 20:42:43] [INFO] Bridge started!
[Dec  7, 2020 20:42:43] [Matrix/INFO] Listening on 127.0.0.1:29318
[Dec  7, 2020 20:42:43] [DEBUG] Updating bot profile
[Dec  7, 2020 20:42:43] [DEBUG] Starting users
[Dec  7, 2020 20:42:43] [DEBUG] Starting custom puppets
[Dec  7, 2020 20:42:43] [User/<<redacted>>/DEBUG] Connecting to WhatsApp
[Dec  7, 2020 20:42:44] [User/<<redacted>>/DEBUG] WhatsApp connection successful
[Dec  7, 2020 20:43:44] [User/<<redacted>>/ERROR] Failed to restore session: admin login errored: 419 (unknown error)
[Dec  7, 2020 20:43:44] [User/<<redacted>>/DEBUG] Disconnecting due to failed session restore...
```

In the last two/three months the bridge could easliy reconnect with the command `reconnect` to the Whats-App (inside an emulator). I cannot simply re-login for this reason.
I did not modify anything close to this setup in the last weeks, this error just popped up today.

**Comment by rreuvekamp** [comment]
It seems WhatsApp randomly logs people out, which results in the error you're getting. (Source: https://github.com/Rhymen/go-whatsapp/issues/268 , which is the library this bridge uses to talk to WhatsApp)

I don't have a fix for you, other than trying to let the bridge re-login to WhatsApp, by doing 'logout' and then 'login' in the bot room.

Hope this helps!

**Comment by Mynacol** [comment]
Thanks. I re-logged in manually and now it works again.
