### ISSUE TITLE
Failed to connect to homeserver: failed to ensure registered:

### ISSUE THREAD

**Issue by DoctorSubtilis** [tulir/mautrix-whatsapp#244]
I get thiw error message, wheb I try to start the bridge 
    [Dec 13, 2020 20:47:59] [ERROR] Failed to connect to homeserver: failed to ensure registered: request error: Post 
    "http://homeserver.example:8008/_matrix/client/r0/register?user_id=%40whatsappbot%3Ahomeserver.example": dial tcp: lookup 
    homeserver.example: no such host. Retrying in 10 seconds...  

### My registration yaml  

id: whatsapp
url: http://localhost:29318
as_token: YTafLoyR4SkZzZ5P1Am0iveSYYZXxZ5ahWAbRO4rRQwNwDMGWhYVsIJc2dGmp8ZZ
hs_token: tCwUbs1kJj2emGk3Ti8wmDssSZYLZ0e1dUK8v6LKsjdUFke3JodTSqe3QOjVUWFK
sender_localpart: jxm77xjAKboXkajqCMybfDhDP8Jt4X2A
rate_limited: false
namespaces:
  users:
  - regex: ^@whatsapp_[0-9]+:homeserver.example$
    exclusive: true
  - regex: ^@whatsappbot:homeserver.example$
    exclusive: true

### my config.yaml

homeserver:
  address: http://homeserver.example:8008
  domain: homeserver.example
  asmux: false
appservice:
  address: http://localhost:29318
  hostname: 0.0.0.0
  port: 29318
  database:
    type: sqlite3
    uri: mautrix-whatsapp.db
    max_open_conns: 20
    max_idle_conns: 2
  provisioning:
    prefix: /_matrix/provision/v1
    shared_secret: disable
  id: whatsapp
  bot:
    username: whatsappbot
    displayname: WhatsApp bridge bot
    avatar: mxc://maunium.net/NeXNQarUbrlYBiPCpprYsRqr
  as_token: YTafLoyR4SkZzZ5P1Am0iveSYYZXxZ5ahWAbRO4rRQwNwDMGWhYVsIJc2dGmp8ZZ
  hs_token: tCwUbs1kJj2emGk3Ti8wmDssSZYLZ0e1dUK8v6LKsjdUFke3JodTSqe3QOjVUWFK
metrics:
  enabled: false
  listen: 127.0.0.1:8001
whatsapp:
  os_name: Mautrix-WhatsApp bridge
  browser_name: mx-wa
bridge:
  username_template: whatsapp_{{.}}
  displayname_template: '{{if .Notify}}{{.Notify}}{{else}}{{.Jid}}{{end}} (WA)'
  community_template: whatsapp_{{.Localpart}}={{.Server}}
  connection_timeout: 20
  fetch_message_on_timeout: false
  delivery_receipts: false
  login_qr_regen_count: 2
  max_connection_attempts: 3
  connection_retry_delay: -1
  report_connection_retry: true
  chat_list_wait: 30
  portal_sync_wait: 600
  user_message_buffer: 1024
  portal_message_buffer: 128
  call_notices:
    start: true
    end: true
  initial_chat_sync_count: 10
  initial_history_fill_count: 20
  initial_history_disable_notifications: false
  recovery_chat_sync_count: -1
  recovery_history_backfill: true
  sync_max_chat_age: 259200
  sync_with_custom_puppets: true
  sync_direct_chat_list: false
  default_bridge_receipts: true
  default_bridge_presence: true
  login_shared_secret: ""
  invite_own_puppet_for_backfilling: true
  private_chat_portal_meta: false
  resend_bridge_info: false
  whatsapp_thumbnail: false
  allow_user_invite: false
  command_prefix: '!wa'
  encryption:
    allow: false
    default: false
    key_sharing:
      allow: false
      require_cross_signing: false
      require_verification: true
  permissions:
    '*': 5
    '@admin:example.com': 0
    example.com: 0
  relaybot:
    enabled: false
    management: '!foo:example.com'
    invites: []
    message_formats:
      m.audio: <b>{{ .Sender.Displayname }}</b> sent an audio file
      m.emote: '* <b>{{ .Sender.Displayname }}</b> {{ .Message }}'
      m.file: <b>{{ .Sender.Displayname }}</b> sent a file
      m.image: <b>{{ .Sender.Displayname }}</b> sent an image
      m.location: <b>{{ .Sender.Displayname }}</b> sent a location
      m.notice: '<b>{{ .Sender.Displayname }}</b>: {{ .Message }}'
      m.text: '<b>{{ .Sender.Displayname }}</b>: {{ .Message }}'
      m.video: <b>{{ .Sender.Displayname }}</b> sent a video
logging:
  directory: ./logs
  file_name_format: '{{.Date}}-{{.Index}}.log'
  file_date_format: "2006-01-02"
  file_mode: 384
  timestamp_format: Jan _2, 2006 15:04:05
  print_level: debug

### maybe the problem i the server name?
Installing in KDE Neon (20.04) I chose duns-server as name; only afterwards I changed tha name modifying the file server_nama.yaml in etc.

**Comment by rreuvekamp** [comment]
> Installing in KDE Neon (20.04) I chose duns-server as name; only afterwards I changed tha name modifying the file server_nama.yaml in etc.

I'm not sure what you mean by this. Could you elaborate please?

The error message is saying 'homeserver.example' is not a valid domain name. You need to be running your own Matrix server (Matrix Synapse) to be able to use the bridge. You should set _homeserver->address:_ in the bridge config.yaml to your own Matrix server. The same domain name other people use to chat with you on Matrix.

**Comment by DoctorSubtilis** [comment]
It's righet that to use your bruidge I have ti use synapse, and to use synapse I have to use ubuntu-server? But ubuntu-server is as SO or as apps, "under" Ubuntu desktop?

**Comment by rreuvekamp** [comment]
I'm afraid we can't really help you here with setting up Synapse correctly. But it's a necessity to have a correctly configured Synapse to use bridges.

I advice you to get your Synapse server setup so that you can use it to chat with others before looking into running bridges. We talked a bit in the matrix community room of the bridge and it seemed to me that don't yet use your matrix server for that.

**Comment by DoctorSubtilis** [comment]
according to other developers I can't instakll synapse on a my remore website: it's correct?
