### ISSUE TITLE
Mautrix-WhatsApp does not work with Dendrite when community_template is not set to null

### ISSUE THREAD

**Issue by phol** [tulir/mautrix-whatsapp#257]
This seems to be related to Dendrite not giving Mautrix-WhatsApp enough permissions to join rooms. I've filed [an issue](https://github.com/matrix-org/dendrite/issues/1711) with details on the [matrix-org/dendrite](https://github.com/matrix-org/dendrite) repository.

**Comment by tulir** [comment]
You probably have to set `community_template` to `null` for servers that don't support communities

**Comment by phol** [comment]
Thank you for your suggestion, now the bot works (although without the community feature of course)!

**Comment by tulir** [comment]
Communities are a legacy feature that's going to be replaced soon, Dendrite won't implement them

**Comment by phol** [comment]
Alright, I wasn't aware of that, thanks. I've created a small pull request so other people can also be aware to disable `community_template` when trying to set this up. 

Do you have any idea what communities will be replaced with or do you maybe have suggestions for other ways to group bridged chats?
