### ISSUE TITLE
Invalid user localpart for this application service

### ISSUE THREAD

**Issue by wuast94** [tulir/mautrix-whatsapp#261]
I get the following error when i try to start the bridge. i added the reg yaml to synapse and restartet, in the reg yaml all domains looks good and the machines can see each other:

failed to POST /_matrix/client/r0/register: M_EXCLUSIVE (HTTP 400): Invalid user localpart for this application service.. Retrying in 10 seconds...

**Comment by tulir** [comment]
Is `homeserver`->`domain` in the config correct? Also, the Matrix room ([#whatsapp:maunium.net](https://matrix.to/#/#whatsapp:maunium.net)) is a better place to debug setup issues.
