### ISSUE TITLE
instalation error

### ISSUE THREAD

**Issue by aermike** [tulir/mautrix-whatsapp#262]
When try install mautrix-whatsapp accordly with 
https://github.com/tulir/mautrix-whatsapp/wiki/Bridge-setup
at build receive that error
mautrix-whatsapp# ./build.sh -tags nosas
# maunium.net/go/mautrix/crypto/olm
/root/go/pkg/mod/maunium.net/go/mautrix@v0.8.0/crypto/olm/account.go:4:11: fatal error: olm/olm.h: No such file or directory
 // #include <olm/olm.h>
           ^~~~~~~~~~~
compilation terminated.

**Comment by DoM1niC** [comment]
Did you installed latest go? so in my case `go build ` works fine here try the direct Path to make sure are you use the newest GO `/usr/lib/go-$GO_VERSION/bin/go build`

**Comment by payne747** [comment]
I also ran into this problem on Debian 10 "Buster", and after installing `libolm-dev` I encountered another error with the missing file `olm/pk.h`.

The fix is to install `libolm-dev` from Debian backports so you get version 3.

**Comment by tulir** [comment]
The original issue was that the `nosas` tag for libolm2 compatibility didn't work, but that has been deprecated, so libolm3 is now required
