### ISSUE TITLE
Docker image for arm32

### ISSUE THREAD

**Issue by neugartf** [tulir/mautrix-whatsapp#266]
I saw that there are only docker images available for arm64, any chance to also publish those for 32bit systems (e.g. raspberry pi)?
If you want me to open a PR, let me know!

**Comment by tulir** [comment]
Raspberry Pi's are 64-bit (model 2B v1.2+, i.e. 2016 and later), you should just switch to a 64-bit OS. Cross-compiling with docker is hard, so I probably won't bother building 32-bit docker images.

**Comment by TheTimeWalker** [comment]
I just want to note that Raspberry Pi OS is still a default 32-bit OS. The 64-bit version is currently in beta since Mai 2020 and not recommended for daily driving by the foundation.

**Comment by neugartf** [comment]
+1 on what @TheTimeWalker said.
I might go ahead and publish 32bit builds on docker.hub if you don't mind.
