### ISSUE TITLE
Failed to create communities with login_shared_secret

### ISSUE THREAD

**Issue by zoomyboy** [tulir/mautrix-whatsapp#268]
I configured the following:

```
    # Localpart template for per-user room grouping community IDs.
    # On startup, the bridge will try to create these communities, add all of the specific user's
    # portals to the community, and invite the Matrix user to it.
    # (Note that, by default, non-admins might not have your homeserver's permission to create
    #  communities.)
    # {{.Localpart}} is the MXID localpart and {{.Server}} is the MXID server part of the user.
    # whatsapp_{{.Localpart}}={{.Server}} is a good value that should work for any user.
    community_template: wa
```
... to just "whatsapp" - because I am the only user on synapse using the bridge. As I understood this correctly, the bridge would invite all my whatsapp rooms to the "wa" community to group them together - which is what I want.

I also set a ``login_shared_secret``. This is working fine, since the bridge automatically sends and accepts room invitations when new chats are synched.

 But the group creation is not working. The logs say that the bridge doesnt authenticate successfully:

```
Server responded with error creating personal filtering community: failed to POST /_matrix/client/r0/create_group: M_UNKNOWN (HTTP 403): Only a server admin can create groups on this server
```

Is the login shared secret even recognised when creating communities? Or does this require a real admin user to be logged in (which is also the case though)..

**Comment by rreuvekamp** [comment]
The answer is there:

> (Note that, by default, non-admins might not have your homeserver's permission to create communities.)

and

> Only a server admin can create groups on this server

By default Synapse doesn't allow non-admins to create communities/groups. There's a setting in homeserver.yaml to allow non-admins to create groups. I think it's enable_group_creation or something. You should be able to find it my reading homeserver.yaml. 

Hope this fixes it! Love to hear

**Comment by zoomyboy** [comment]
This worked. Thanks a lot.
