### ISSUE TITLE
out of memory error and subsequent not able to start anymore

### ISSUE THREAD

**Issue by kumarunster** [tulir/mautrix-whatsapp#271]
Hello, I'm running this project as docker container in my evaluation matrix instance.

since today I'm receiving following errors. the docker container does not starting anymore. Any suggestions?
[oom-1.log](https://github.com/tulir/mautrix-whatsapp/files/5961435/oom-1.log)

[restart-error.log](https://github.com/tulir/mautrix-whatsapp/files/5961448/restart-error.log)

What could it be?

**Comment by tulir** [comment]
That looks like a docker issue that isn't directly related to the bridge

**Comment by kumarunster** [comment]
thanks for that quick response.
I can't see any huge memory usage in docker containers:
```
CONTAINER ID   NAME                    CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
719fb104f69e   matrix-synapse          0.46%     196.8MiB / 985.2MiB   19.98%    172MB / 241MB     35.4GB / 0B       17
f38569d83557   matrix-postgres         0.22%     92.39MiB / 985.2MiB   9.38%     201MB / 105MB     38.5GB / 3.8GB    17
026765c145b1   matrix-nginx-proxy      0.00%     3.336MiB / 985.2MiB   0.34%     318MB / 305MB     8.35GB / 0B       2
40cc614258f2   matrix-client-element   0.00%     2.266MiB / 985.2MiB   0.23%     684kB / 36.4MB    91.3MB / 0B       2
bcf0800c4810   matrix-registration     0.03%     39.38MiB / 985.2MiB   4.00%     42.8kB / 70.7kB   11.7GB / 0B       5
e273dc0a3c99   matrix-synapse-admin    0.00%     2.246MiB / 985.2MiB   0.23%     34.8kB / 0B       6.45MB / 8.19kB   2
23036e9a4805   matrix-coturn           0.06%     12.36MiB / 985.2MiB   1.25%     187kB / 262kB     13.9GB / 0B       7
35a6daf61650   matrix-mailer           0.00%     1.285MiB / 985.2MiB   0.13%     35.1kB / 0B       2.36GB / 0B       2
```

I even not seeing any significant spikes today in monitoring. It just died after processing one message and now does not start anymore. all other container seems to work as expected. However I did a whole docker setup restart and it now it seems to backup again.

Thanks.
