### ISSUE TITLE
Relaybot - Not handling: message is duplicate on first whatsapp message

### ISSUE THREAD

**Issue by mtcoliveira** [tulir/mautrix-whatsapp#275]
Hello guys&girls

I have an installation of Matrix Home Server and mautrix-whatsapp bridge, both are set via docker and both running the latest versions to date (02/22/2021).
Despite this one problem, the rest is working normally.

The problem happens when I receive the first message from a new contact (someone who had never sent a message through whatsapp before). I receive the invitation of the room sent by relayagent, i can connect to the room normally and view the message the contact sent, but when i try to reply the message, the message ins´t sent back to the whatsapp contact.

Doing some tests I managed to get the error that is generated as soon as the person sends that first message:

[Feb 22, 2021 19:41:11] [Portal/xxxxxxxxxxxxx@s.whatsapp.net-xxxxxxxxxxxx@s.whatsapp.net/DEBUG] Not handling 3A9200C2CE592E6F9A72: message is duplicate

(I changed the whatsapp numbers just for sefaty)

Could someone help me with this problem?

**Comment by mtcoliveira** [comment]
nobody?

**Comment by dbedoya** [comment]
We have the same issue with the realyboy, messages to new users are not bridged, although we don't think it is related to duplicated messages. We managed to make it work by changing the code to insert a record in the table user_portal after the new room is created. We have this open PR #273 if you want to take a look. And issue #225 seems to be related to this too.

**Comment by mtcoliveira** [comment]
> We have the same issue with the realyboy, messages to new users are not bridged, although we don't think it is related to duplicated messages. We managed to make it work by changing the code to insert a record in the table user_portal after the new room is created. We have this open PR #273 if you want to take a look. And issue #225 seems to be related to this too.

Thx @dbedoya. Problem solved.
