### ISSUE TITLE
Relaybot Room Names

### ISSUE THREAD

**Issue by mtcoliveira** [tulir/mautrix-whatsapp#277]
Hello folks, 

Is there any way to change the default name of the rooms and conversations created by Relayagent?

My problem is that I'm putting 7 other people to automatically join a conversation via whatsapp contact and the name of the room automatically gets: "Person 1 and 7 others ...."

Would there be a way for the room to automatically get the WhatsApp contact name automatically regardless of the number of other people in the same room?

**Comment by tulir** [comment]
https://github.com/tulir/mautrix-whatsapp/blob/master/example-config.yaml#L176-L179

**Comment by mtcoliveira** [comment]
Great @tulir thx a lot. Works like a charm.
