### ISSUE TITLE
[Feature] Support new Voice Messages from Matrix <-> Element Clients

### ISSUE THREAD

**Issue by DoM1niC** [tulir/mautrix-whatsapp#286]
**lagecy | old:** Audios doesn't work anymore, I can't send any sound files, I tried AAC / Opus / MP3 without success.... 
I hope you could research or tell me whats wrong, Videos and Images are fine .... 

I use the **master Branch** of Mautrix-WA / Matrix Synapse **->** FluffyChat with Opus Codes as Sound Recorder, Playback in Matrix works fine so far, **WhatsApp** Business is in use as Client in a **Android-x86 VM**. 

**Issue:** WhatsApp don't show any sendet file 
_equal to #281_

**Updated:** Voice Message supported now matrix-org/matrix-doc#2516

**Comment by DoM1niC** [comment]
Matrix / Element Web are now fully Voice Message supported https://github.com/matrix-org/matrix-doc/pull/2516

I hope this could be a better way to make Appservice handle Voice files

**Comment by DoM1niC** [comment]
Commit https://github.com/tulir/mautrix-whatsapp/tree/3eb5f440239de430830a74a2974edfd81461c2f9 solved this THX <3 @tulir

**Comment by joao-p-marques** [comment]
Hi, I am commenting here as it is the closest issue to my question.

After this change, I can indeed send voice messages from Element and they get handled correctly as voice messages in Whatsapp :tada:. 

However, when I receive a voice message from Whatsapp, it still gets displayed as an audio file in Element. Is there a way to make the Bridge publish those messages as Matrix Voice Messages?

**Comment by DoM1niC** [comment]
fully fixed by PR #418 418
