### ISSUE TITLE
can't generate /mautrix-whatsapp registration.yaml 

### ISSUE THREAD

**Issue by aermike** [tulir/mautrix-whatsapp#290]
Hi 
I truy to config mautrix-whatsapp with postegres database, and got tis error

config.yaml has this line
    # Database config.
    database:
        # The database type. "sqlite3" and "postgres" are supported.
        type: postgres
        # The database URI.
        #   SQLite: File name is enough. https://github.com/mattn/go-sqlite3#connection-string
        #   Postgres: Connection string. For example, postgres://user:password@host/database?sslmode=disable
        #uri: mautrix-whatsapp.db
        #postgres://whatsapp_bot:[password for user whatsapp_bot
![matrix](https://user-images.githubusercontent.com/4247309/111901383-75926300-8a40-11eb-86fb-7c3b5df14f3c.png)
]@localhost/whatsapp?sslmode=disable
        uri: postgres://whatsapp_bot:[password for user whatsapp_bot]@localhost/whatsapp
        # Maximum number of connections. Mostly relevant for Postgres.
        max_open_conns: 20
        max_idle_conns: 2

**Comment by tulir** [comment]
That looks like your config has a syntax error. Debugging setup issues should be done in the Matrix room (and to debug syntax issues, you need to provide the config in some paste service so it would keep the exact formatting. Redact any secret tokens though)
