### ISSUE TITLE
videos (mp4) received through WhatsApp cannot be played or downloaded

### ISSUE THREAD

**Issue by ykktrcb7** [tulir/mautrix-whatsapp#295]
## Description
1. receive video in WhatsApp 
2. video is bridged to Matrix
3. video cannot be played or downloaded

## Screenshot
![videos](https://user-images.githubusercontent.com/81748597/113436004-340c9b00-93e4-11eb-9f09-b8e06c7a4c90.png)

## Version
mautrix-whatsapp v0.1.5+dev.9b25e26b

**Comment by tulir** [comment]
This is most likely a bug in your client

**Comment by ykktrcb7** [comment]
This happens in both Element clients (web and Android)

-------- Original Message --------

**Comment by tulir** [comment]
Element web is broken, but are you sure it doesn't work on Android? It doesn't have a preview, but should be playable.

**Comment by ykktrcb7** [comment]
You are right, Android preview is broken. I have to open media like a PIC and swipe through the videos.

We can close the issue and I will open in the clients,  if they don't exist already.

**Comment by tulir** [comment]
I made a PR to fix element web: matrix-org/matrix-react-sdk#5826
