### ISSUE TITLE
Rooms are created for persnal chats

### ISSUE THREAD

**Issue by zoomyboy** [tulir/mautrix-whatsapp#297]
Hey people,

I configured the bridge to automatically  invite me to matrix rooms via a shared key.
However, a personal chat with one person is sometimes created as a room with only myself and that person and sometimes as just a person without a room. This is very inconvenient because personal chats are among the real whatsapp group chats.
Can I fix this problem somehow and resync my whole database afterwards?

**Comment by pagdot** [comment]
I've got the same issue. Did you manage to resolve it? If yes, how?
