### ISSUE TITLE
Bridge Bot des not responde anymore

### ISSUE THREAD

**Issue by FirstWithThisName** [tulir/mautrix-whatsapp#299]
The logs do not show any errors.

'
@user:matrix.addr sent 'status' in !roomdi:matrix.addr 
'

**Comment by tulir** [comment]
Are you sure it didn't send an "unknown command" response?

**Comment by FirstWithThisName** [comment]
![a](https://user-images.githubusercontent.com/40352786/115920208-2940a580-a47a-11eb-89aa-d5d96ef565ca.png)

**Comment by tulir** [comment]
Did you ignore the bot?

**Comment by FirstWithThisName** [comment]
@tulir I don't understand

**Comment by FirstWithThisName** [comment]
Compiled now the latest version from git, but same result.

**Comment by FirstWithThisName** [comment]
```go
// Reply sends a reply to command as notice
func (ce *CommandEvent) Reply(msg string, args ...interface{}) {
        content := format.RenderMarkdown(fmt.Sprintf(msg, args...), true, false)
        ce.Handler.log.Debugfln("DDD")
        content.MsgType = event.MsgNotice
        intent := ce.Bot
        if ce.Portal != nil && ce.Portal.IsPrivateChat() {
                ce.Handler.log.Debugfln("D111")
                intent = ce.Portal.MainIntent()
        }

        ce.Handler.log.Debugfln("EEE")
        _, err := intent.SendMessageEvent(ce.RoomID, event.EventMessage, content)
        if err != nil {
                ce.Handler.log.Warnfln("Failed to reply to command from %s: %v", ce.User.MXID, err)
        }
        ce.Handler.log.Debugfln("FFF")
}
```
FFF gets printed.    
I have no experience in go, but my guess it that "intent.SendMessageEvent" contains a bug.
Unfortunately I did not find the implementation of SendMessageEvent.

**Comment by tulir** [comment]
Ignoring means clicking the "Ignore" button so you don't see any of the user's messages

**Comment by FirstWithThisName** [comment]
No I didn't. If I did would not be able to send messages to bridge anyway, or am I wrong?

**Comment by tulir** [comment]
Ignoring doesn't affect sending messages, it only hides incoming messages from that user. You can unignore by clicking on the user in the right panel user list and clicking unignore

**Comment by FirstWithThisName** [comment]
Thank you very much tulir, you are right.   
I have no idea why this happend.  
Sorry for this noobie questions, but I just did not know that is possible.

**Comment by cboseck** [comment]
Hello, now I know why the whatsapp-bridge-bot was set to ignore.
I ignored, the whatsapp-broadcast.

**Comment by Redskyer** [comment]
I've got the same problem. But the bot is not ignored. I've tried to ignore and unignore him, but nothing changed.
I don't get any messages and can't see any problems in the log.

Do you have any other idea?

**Comment by Redskyer** [comment]
> I've got the same problem. But the bot is not ignored. I've tried to ignore and unignore him, but nothing changed. I don't get any messages and can't see any problems in the log.
> 
> Do you have any other idea? ![Screenshot 2022-04-26 120402](https://user-images.githubusercontent.com/43165480/165276182-6ad9cf6a-eff8-49b9-b113-2ed24d244301.png)

I now what the problem was. I've used http://localhost:29318 instead of using the internal IP from the docker container. Now I can communicate with my bot :D
