### ISSUE TITLE
Failed to update

### ISSUE THREAD

**Issue by saxtorinc** [tulir/mautrix-whatsapp#31]
Hello could you help me out here? Please
 Failed to update bot avatar: msg=Failed to PUT JSON to /_matrix/client/r0/profile/@whatsappbot:matrix.org/avatar_url code=401 wrapped=M_UNKNOWN_TOKEN: Invalid macaroon passed

**Comment by tulir** [comment]
I think this was resolved elsewhere. For setup issues, asking in [#whatsapp:maunium.net](https://matrix.to/#/#whatsapp:maunium.net) is better
