### ISSUE TITLE
the pickled object is too new

### ISSUE THREAD

**Issue by neferin12** [tulir/mautrix-whatsapp#312]
I compiled the bridge myself and when I try running it i get the following error:
`[Jun 11, 2021 18:36:27] [FATAL] Error initializing end-to-bridge encryption: the pickled object is too new`
I hope i didn't miss something simple but I am a bit of a noob when it comes to matrix, and have honestly no clue what that message means, and asking google brought no success. The database the bridge is connected to is from the prebuild version I used before.

**Comment by tulir** [comment]
You downgraded to an older version of libolm, so it can't read the stored encryption keys anymore.

**Comment by neferin12** [comment]
okay, Thank you very much
