### ISSUE TITLE
Can't connect to WA: Unknown error while reconnecting

### ISSUE THREAD

**Issue by phuhl** [tulir/mautrix-whatsapp#313]
Error message is:

`Unknown error while reconnecting: error decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {}`

**Comment by tulir** [comment]
That probably means you're using an outdated version of the bridge.

**Comment by JAicewizard** [comment]
I also just got this error! I am using an old version. I will update later today to see if that fixes it.

**Comment by zoomyboy** [comment]
I upgraded like an hour ago ut that didn't fix it. Still getting this error

**Comment by JAicewizard** [comment]
updating works for me. running `mautrix-whatsapp (https://github.com/tulir/mautrix-whatsapp) v0.1.7 (https://github.com/tulir/mautrix-whatsapp/releases/v0.1.7) (Jun 16 2021, 15:59:10)` atm

**Comment by zoomyboy** [comment]
Sorry. I forgot to recompile. Works now. However, as I reconnected from whatsapp, it's trying to sync to already existing rooms:

```
Failed to invite @ to +wa_YYY: failed to PUT /_matrix/client/r0/groups/+XXX/admin/users/invite/@whatsapp_XXX: M_BAD_STATE (HTTP 400):
User already invited to group
```

**Comment by phuhl** [comment]
Update worked for me, too. Thanks for the info and sorry for not checking before creating the issue.

@tulir Maybe, to keep the amount of issues related to this low, the error message could contain a hint, that updating the wa-bridge might be nessecary?

**Comment by JAicewizard** [comment]
updating is usually a first thing you should do, after checking if any issues are already posted, and making sure the new update doesn't break anything you use.

**Comment by phuhl** [comment]
Sure, will do in the future. It was just a thought, to make sure, you guys have as few unnecessary issues opened as possible :)
