### ISSUE TITLE
Compiled file

### ISSUE THREAD

**Issue by Carlosbarros967** [tulir/mautrix-whatsapp#318]
hello tulir

Will the file compiled as in previous versions come out?

**Comment by Carlosbarros967** [comment]
![image](https://user-images.githubusercontent.com/86306269/122938701-5cec5e80-d349-11eb-8ce3-d33f24dd806d.png)

**Comment by tulir** [comment]
Added, but you can always just download binaries directly from mau.dev

**Comment by Carlosbarros967** [comment]
Obrigado Tulir
