### ISSUE TITLE
Matrix direct chats instead of rooms

### ISSUE THREAD

**Issue by F13** [tulir/mautrix-whatsapp#326]
Hi,

Is it possible to configure the bridge to use direct chat with whatsapp users, instead of a 2-person room? At least in the case of the Element client, the UI separates out individuals (People) from rooms. mautrix-signal and mautrix-hangouts both handle this as I'd expect, but this whatsapp bridge configures a room instead of a DM.

Is there a configuration step I'm missing?

Thanks!

**Comment by F13** [comment]
Well, nevermind. I left the room and started a new direct chat and that worked just fine, so I'm not sure what I did incorrectly the first time!

**Comment by Severin-S** [comment]
On Element Desktop you can use `/converttodm` and `/converttoroom` when a chat is in the wrong category.

To prevent this, you can try setting `sync_direct_chat_list` to true in the config. I'm not entirely sure whether that helps, but tulir mentioned this option in context of a similar issue in one of the mautrix Matrix rooms recently.
