### ISSUE TITLE
Integrate improvements into Rhymen/go-whatsapp?

### ISSUE THREAD

**Issue by KrzysztofMadejski** [tulir/mautrix-whatsapp#33]
HI @tulir , hi @Rhymen, how are you? Thank you for the great work you did on WhatsApp handling in Go.

I'm now working on WhatsApp bridge for Matterbridge: https://github.com/42wim/matterbridge/issues/475

It would be great to reuse the improvements / extra features @tulir you have built on top of https://github.com/Rhymen/go-whatsapp in https://github.com/tulir/mautrix-whatsapp/tree/master/whatsapp-ext.

For now I'm importing `mautrix-whatsapp/whatsapp-ext`, but I think it would be valuable for other reusers to keep WhatsApp related code in one library. That would require some work on @Rhymen side also, so I wonder if you had chatted about it and what do you think about it?

All the best!

**Comment by KrzysztofMadejski** [comment]
CC @SchulteMK

**Comment by tulir** [comment]
The whatsapp-ext package has been merged into https://github.com/tulir/go-whatsapp now
