### ISSUE TITLE
Messages taking forever to load (probably stuck somewhere)

### ISSUE THREAD

**Issue by chagai95** [tulir/mautrix-whatsapp#331]
This happens to me a lot so I can reproduce easily.

The loading spinner just does not stop spinning.

![image](https://user-images.githubusercontent.com/31655082/127733312-0df287b9-90e9-4b75-83ab-c228aa713bb6.png)

https://chagai.website/spinner-does-not-stop-spinning.mp4

[synapse.log](https://github.com/tulir/mautrix-whatsapp/files/6910870/synapse.log)

[whatsapp.log](https://github.com/tulir/mautrix-whatsapp/files/6910871/whatsapp.log)

**Comment by tulir** [comment]
Bridges aren't involved in clients loading room history from the homeserver
