### ISSUE TITLE
docker-android instead of Android Studio

### ISSUE THREAD

**Issue by Evidlo** [tulir/mautrix-whatsapp#38]
This may be a slightly easier alternative to Android Studio: https://github.com/budtmo/docker-android

**Comment by derEisele** [comment]
Nice Docker container, but what about https://anbox.io/ ? It uses no emulator and runs Android in a lxc container natively. I haven't tested WhatsApp yet, but it looks promising.

**Comment by anoadragon453** [comment]
One problem is getting the app to scan the QR code though. Do these solutions allow you to pass through your webcam?

**Comment by tulir** [comment]
This is more of a documentation thing and not a repo issue. If anyone figures out a better alternative for virtual androids, feel free to edit the wiki page or create a new one.
