### ISSUE TITLE
Error on go build

### ISSUE THREAD

**Issue by loi219** [tulir/mautrix-whatsapp#39]
I've follow the instructions from: https://github.com/tulir/mautrix-whatsapp/wiki/Bridge-setup and tried with this command too: `go get -u maunium.net/go/mautrix-whatsapp`

And i've got this error
`../golang/src/maunium.net/go/mautrix/format/markdown.go:7:2: cannot find package "github.com/russross/blackfriday/v2" in any of:
        /usr/lib/go-1.7/src/github.com/russross/blackfriday/v2 (from $GOROOT)
        /home/sven/golang/src/github.com/russross/blackfriday/v2 (from $GOPATH)
commands.go:26:2: cannot find package "maunium.net/go/maulogger/v2" in any of:
        /usr/lib/go-1.7/src/maunium.net/go/maulogger/v2 (from $GOROOT)
        /home/sven/golang/src/maunium.net/go/maulogger/v2 (from $GOPATH)
sven@renard:~/mautrix-whatsapp$`

**Comment by tulir** [comment]
Outdated Go
