### ISSUE TITLE
DM rooms created during initial synchronisation silently discard sent messages.

### ISSUE THREAD

**Issue by ara4n** [tulir/mautrix-whatsapp#45]
I set it up and ran `sync --create`, which invited me to a bunch of promising looking DMs with 1-2 messages of scrollback in each one.  I then tried to send messages in these rooms, but they were silently discarded by the AS.  When new messages from the same users arrive, they invited me to a new DM room rather than using the existing one, and things then behaved correctly in the new room.

**Comment by tulir** [comment]
This was probably fixed some time ago
