### ISSUE TITLE
Question about WhatsApp in a non-private room

### ISSUE THREAD

**Issue by vmario89** [tulir/mautrix-whatsapp#46]
Hi,
at the moment the WhatsApp Bot only can be used one to one (in a private chat/room). I have a senseful use case where i could need to put a WhatsApp Account into a group with many other people. That case is our Whatsapp business account which is used by more than one privileged person and in our case this account is not put to a mobile phone number,  but to a landline call number. We like to share the output (the received messages from the people who are going to write us) to a matrix group. 

Alternative would be to have some kind of bot redirect. A bot which forwards each received message to a user in the target group or something like that.

Are there any plans to deal for something like this?

kind regards, Mario

**Comment by tulir** [comment]
Sounds like you want relaybot support where one Whatsapp account can be chosen to relay messages for Matrix users who haven't logged in. The issue for that is #20 

If you just want Whatsapp->Matrix bridging for that account, you can technically already do that by taking the as_token and inviting users or changing power levels with it.

**Comment by ndom91** [comment]
@vmario89 did you ever figure out how to do this? If not, I just got somethign like you described working by inviting other matrix users to a whatsapp group chat portal. You just have to do it via the API, by using the access token from your whatsapp bot (available in its config.yaml as `as_token`).

Then execute a command like so:

```
curl -XPOST -d '{"user_id":"@yourfriend:chat.domain.com"}' "https://chat.domain.com/_matrix/client/r0/rooms/%21234234234:chat.domain.com/invite?access_token=BOT_AS_TOKEN"
```
Where `234234234:chat.domain.com` is the room id

**Comment by vmario89** [comment]
hi, thanks for your feedback. no i did not try again yet :-(  but i did open another issue some weeks ago because there is some relaybot now but there is no documentation about it - so no idea how to use. https://github.com/tulir/mautrix-whatsapp/issues/131

seems this project is not used enough because the user feedback is really rare to a lot of topics

regards, MArio
