### ISSUE TITLE
Leaving a group chat from Matrix should let WhatsApp leave the group chat too

### ISSUE THREAD

**Issue by PureTryOut** [tulir/mautrix-whatsapp#47]

**Comment by ptman** [comment]
I think it would be nice to be able to leave groups over the bridge, but OTOH would like to not automatically do so.

**Comment by PureTryOut** [comment]
Why not exactly? If you leave the room, you clearly don't want to be a part of it anymore. Seems to be a bit of cheating to be able to leave the room, but read everything you've missed once you come back.

**Comment by ptman** [comment]
Whatsapp has this archive feature without a direct analog in matrix. And I often want to archive 1-to-1 discussions, which would immediately open a new discussion anyway. And clients can log, so even access to old discussion isn't really an argument.

**Comment by PureTryOut** [comment]
Yessss!!! Thanks!
