### ISSUE TITLE
Errors downloading media

### ISSUE THREAD

**Issue by vmario89** [tulir/mautrix-whatsapp#48]
Hi,

bridge works fine except that logs shows some media download errors. I think they appear on voice messages.

i already raised up the max file size in matrix-synapse to 128MB - made no difference.
Any idea?

Mär 14 04:41:55 h2606131.stratoserver.net mautrix-whatsapp[24633]: [Mar 14, 2019 04:41:55] [Portal/SOMENUMBERIVEHIDDDEN@s.whatsapp.net-MYNUMBERISHIDDEN@s.whatsapp.net/ERROR] Failed to download media: download failed
Mär 14 04:41:55 h2606131.stratoserver.net mautrix-whatsapp[24633]: [Mar 14, 2019 04:41:55] [Portal/SOMENUMBERIVEHIDDDEN@s.whatsapp.net-MYNUMBERISHIDDEN@s.whatsapp.net/ERROR] Failed to download media: download failed
Mär 14 04:41:55 h2606131.stratoserver.net mautrix-whatsapp[24633]: [Mar 14, 2019 04:41:55] [Portal/SOMENUMBERIVEHIDDDEN@s.whatsapp.net-MYNUMBERISHIDDEN@s.whatsapp.net/ERROR] Failed to download media: download failed
Mär 14 04:41:55 h2606131.stratoserver.net mautrix-whatsapp[24633]: [Mar 14, 2019 04:41:55] [Portal/SOMENUMBERIVEHIDDDEN@s.whatsapp.net-MYNUMBERISHIDDEN@s.whatsapp.net/ERROR] Failed to download media: download failed
Mär 14 04:41:55 h2606131.stratoserver.net mautrix-whatsapp[24633]: [Mar 14, 2019 04:41:55] [Portal/SOMENUMBERIVEHIDDDEN@s.whatsapp.net-MYNUMBERISHIDDEN@s.whatsapp.net/ERROR] Failed to download media: download failed
Mär 14 04:41:55 h2606131.stratoserver.net mautrix-whatsapp[24633]: [Mar 14, 2019 04:41:55] [Portal/SOMENUMBERIVEHIDDDEN@s.whatsapp.net-MYNUMBERISHIDDEN@s.whatsapp.net/ERROR] Failed to download media: download failed
Mär 14 04:41:55 h2606131.stratoserver.net mautrix-whatsapp[24633]: [Mar 14, 2019 04:41:55] [Portal/SOMENUMBERIVEHIDDDEN@s.whatsapp.net-MYNUMBERISHIDDEN@s.whatsapp.net/ERROR] Failed to download media: download failed

the phone numbers i removed from the log

regards, Mario

**Comment by tulir** [comment]
This means error downloading whatsapp media. I probably need to edit go-whatsapp a bit to figure out the actual error.

**Comment by gzlivre** [comment]
it may be related to this
https://www.theguardian.com/technology/2019/mar/13/facebook-outages-americas-europe-instagram-whatsapp

**Comment by vmario89** [comment]
Hi,
the problem is still persistent. i already recognized this behaviour when setting up the bridge first 2 weeks ago. The facebook unavailibitly should nothing have to do with this. But thanks for the info :)

regards, Mario

**Comment by vmario89** [comment]
i am closing this because it did not occure again
