### ISSUE TITLE
autosync

### ISSUE THREAD

**Issue by vmario89** [tulir/mautrix-whatsapp#51]
Hey, i am testing the bridge for some weeks now and recognized that sometimes i get messages to native whatsapp platform, which are sent recognized by my matrix server. I am able to retrieve those "lost" messages typing "sync --create" into the bot chat. 

Is it possible to have some kind of automatic sync? If the user does not know he is missing answers from other persons, we will never get them except he enters "sync" again to get more messages.

by the way it would be good to get some bot feedback when entering "sync". So the bot could answer "syncing ... please wait" or something like that. Because syncing is sometimes slow and takes some minutes, the users wonders if it will do anything or could think its broken.

regards, Mario

**Comment by olmari** [comment]
Well in general that seems more like a bug in delivery... In theory there never should be need for sync after initial sync... But things do happend sometimes... My .02, and not even any kind of solution (:

**Comment by tulir** [comment]
Yeah, `sync` only syncs contacts/groups, not messages. There might be something else wrong

**Comment by vmario89** [comment]
i am closing issue.just related to the fact that whatspp bridge panics after a while
