### ISSUE TITLE
"login" without creating invitations for each contact

### ISSUE THREAD

**Issue by jacotec** [tulir/mautrix-whatsapp#56]
I'd like the opportunity to not have the "login" command creating loads of invitations by getting history data from whatsapp.

When a user just wants to bridge 2-3 of his important WA chats to Matrix, the initial "login" will create like 80 invitations for all his WA contacts and he needs to refuse 77 invites to have the 3 contacts he'd like to have in Matrix remaining.

In my opinion it would be good to have the login command preventing the creation of invites, just updating the database of the bridge for that user. So a user can add his wanted chats with:

```
login
sync
list
pm xxxxx
pm xxxxx
pm xxxxx

```

The history could get fetched when a user really creates a room with a WA contact (with sync --create or pm xxxx).

**Comment by tulir** [comment]
I think the `initial_chat_sync_count` and `sync_chat_max_age` config options should mostly cover this.

**Comment by arseniybanayev** [comment]
What is the answer to this question today? I'm using the popular spantaleev ansible playbook and I'm getting this behavior upon first `login`, which I don't think is a great user experience. However, no combination of config variables achieves this. If we're waiting for MSC2716, what is the recommended way to achieve this today (i.e., how can we reproduce `initial_chat_sync_count: 0` from before)?

**Comment by tulir** [comment]
Set `history_sync` -> `create_portals` to `false` (and make sure `backfill` is `false` too, although that's the default).

**Comment by arseniybanayev** [comment]
Nice, thank you @tulir! Is there a way to create rooms for all the non-direct group chats that someone has in WhatsApp upon first `login`? Or is there a command that can be issued to do this?

**Comment by Severin-S** [comment]
The command `sync groups` creates rooms for *all* Whatsapp group chats .

**Comment by arseniybanayev** [comment]
Hmm, it doesn’t seem to be creating any rooms for grope chats. Is there a log I can share that would help diagnose?

--
Arseniy Banayev
(407) 462-0998 | Connect on LinkedIn <https://www.linkedin.com/in/arseniy-banayev/>
Schedule a meeting: https://calendly.com/banayev <https://calendly.com/banayev>
