### ISSUE TITLE
Bridge looses messages which are delivered on restart

### ISSUE THREAD

**Issue by jacotec** [tulir/mautrix-whatsapp#57]
The bridge occasionally looses messages which are not delivered to Matrix. When the bridge is restarted, these missed messages are delivered (but they are not in the right order then in Riot).

Initially reported by olmari in the Matrix room, I can confirm this issue.

**Comment by olmari** [comment]
Yeah, within 24hour perioid the bridge definately dies "on its own", bridge log is kind of lacking, it has only one line after all the stuff that has worked above it:

```
maalis 25 19:56:36 matrix mautrix-whatsapp[28656]: [Mar 25, 2019 19:56:36] [User/@olmari:hacklab.fi/DEBUG] JSON message: ["Stream","asleep"]
maalis 25 20:48:47 matrix mautrix-whatsapp[28656]: [Mar 25, 2019 20:48:47] [User/@olmari:hacklab.fi/ERROR] WhatsApp error: connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF
```

**Comment by tulir** [comment]
I'd assume this has been fixed with automatic reconnection and backfilling
