### ISSUE TITLE
Inject messages with corresponding time sent on Whatsapp

### ISSUE THREAD

**Issue by anoadragon453** [tulir/mautrix-whatsapp#59]
When the bridge hangs and is restarted, a flurry of messages come in, all being sent at the current time. This time doesn't match up with when they were actually sent on WhatsApp, and thus causes confusing about when these messages actually were sent.

Appservices have the ability [to inject their own timestamps](https://matrix.org/docs/spec/application_service/r0.1.0.html#timestamp-massaging) to solve this problem. Hopefully the bridge can make use of this as well, assuming WhatsApp tells you the time the message was actually sent.

**Comment by tulir** [comment]
Both of my bridges already do timestamp massaging.

As the spec you linked says,

> Previous drafts of the Application Service API permitted application services to alter the timestamp of their sent events by providing a ts query parameter when sending an event. **This API has been excluded** from the first release due to design concerns, however some servers may still support the feature. Please visit issue matrix-org/matrix-doc#1585 for more information.
