### ISSUE TITLE
How to deploy this bridge on a 3rd-party hosted rom?

### ISSUE THREAD

**Issue by Retrochet** [tulir/mautrix-whatsapp#61]
I notice that installing the bridge needs to
```
Add the path to the registration file to your synapse homeserver.yaml under app_service_config_files.
```  
Is that mean the bridge can't be use in on servers which is provided by matrix.org or whatever?
And if I was wrong , plz give me a hint to deploy this bridge in this case

**Comment by PureTryOut** [comment]
> Is that mean the bridge can't be use in on servers which is provided by matrix.org or whatever?

Yes, you need to own a homeserver if you want to host this bridge.
