### ISSUE TITLE
Don't log private information by default

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-whatsapp#63]
Logs currently contain message content and other private information. The logs should be minimized to contain as little private information as possible without reducing usefulness when debugging.

**Comment by evilham** [comment]
Related question but unsure if it should be a different Issue: It looks to me like setting:
```
logging:
  print_level: error
```
does not actually affect the logging level and from my basic Go understanding I didn't find a place where this setting is used or the config is passed to maulogger.

Am I looking wrong at things? If not, is that part of this issue?

**Comment by Toxyl** [comment]
I'm seeing the same behavior and judging by this issue it has been like this for 2 years? Why is this not fixed? It should not be possible for an admin to just have plaintext logging of his/her users' messages. And even if possible, it should really not be the default setting.

**Comment by tulir** [comment]
This issue was fixed over a year ago

**Comment by Toxyl** [comment]
Well, I've installed this last December from the repo's master branch.

**Comment by Toxyl** [comment]
And debug logging is still the default setting, see https://github.com/tulir/mautrix-whatsapp/blob/master/example-config.yaml#L258

**Comment by tulir** [comment]
The issue was primarily about message content, which is not logged even on the debug level. I might add a trace level below debug in the future that does log message content, but haven't got around to it yet.

**Comment by Toxyl** [comment]
It certainly is being logged, I saw it today. That's why I responded to the issue. I was able to read messages from ANY user on my server using the WhatsApp bridge. They are not logged to the log files of the bridge, but they show up in the syslog and can be seen when following the journal (`journalctl -u your-server -f`).
