### ISSUE TITLE
SSL is not enabled on the server

### ISSUE THREAD

**Issue by BrechtSerckx** [tulir/mautrix-whatsapp#65]
I've installed the docker image for mautrix-whatsapp, but I am getting the following error:

     Failed to initialize database: pq: SSL is not enabled on the server

I used the same method to set up mautrix-whatsapp as with mautrix-telegram, which works fine. Any idea what this could be?

**Comment by BrechtSerckx** [comment]
Found it: the URI for postgres must be in the following format:

    uri: 'host=HOST user=USER password=PASSWORD dbname=DBNAME sslmode=disable'

**Comment by tobymurray** [comment]
I also ran into this, looking at a config.yaml that had the comments stripped out. Before they're stripped out they contain this helpful line:
> For example, postgres://user:password@host/database?sslmode=disable
