### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by iexos** [tulir/mautrix-whatsapp#69]
Using latest commit `c4186c9029`, i get this every time on start:

```
[2019-06-08 18:02:34] [DEBUG] Initializing state store
[2019-06-08 18:02:34] [DEBUG] Initializing database
[2019-06-08 18:02:34] [DEBUG] Initializing Matrix event processor
[2019-06-08 18:02:34] [DEBUG] Initializing Matrix event handler
[2019-06-08 18:02:34] [INFO] Bridge initialization complete, starting...
[2019-06-08 18:02:34] [Database/Upgrade/INFO] Database currently on v8, latest: v8
[2019-06-08 18:02:34] [DEBUG] Starting application service HTTP server
[2019-06-08 18:02:34] [DEBUG] Starting event processor
[2019-06-08 18:02:34] [INFO] Bridge started!
[2019-06-08 18:02:34] [Matrix/INFO] Listening on 172.16.238.3:8010
[2019-06-08 18:02:34] [DEBUG] Updating bot profile
[2019-06-08 18:02:34] [DEBUG] Starting users
[2019-06-08 18:02:34] [DEBUG] Starting custom puppets
[2019-06-08 18:02:34] [User/@iexos:iexos.net/DEBUG] Connecting to WhatsApp
[2019-06-08 18:02:34] [Database/Puppet/ERROR] Database scan failed: sql: Scan error on column index 4, name "name_quality": converting driver.Value type []uint8 ("") to a int64: invalid syntax
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8c7de8]

goroutine 39 [running]:
main.(*Bridge).dbPuppetsToPuppets(0x40000c7340, 0x4000010038, 0x1, 0x1, 0x0, 0x0, 0x0)
        /build/puppet.go:110 +0xc0
main.(*Bridge).GetAllPuppetsWithCustomMXID(0x40000c7340, 0x40000202b0, 0x1, 0x1)
        /build/puppet.go:98 +0x3c
main.(*Bridge).StartUsers(0x40000c7340)
        /build/main.go:201 +0x154
created by main.(*Bridge).Start
        /build/main.go:168 +0x23c
```

I am building via the provided Dockerfile on arm64. This is a regression introduced in one of the last commits, if necessary I can narrow it down to when exactly.

**Comment by derjames** [comment]
At least 2 users had the same problem in #whatsapp:maunium.net. 
As the error message suggests there is something wrong with a database entry. 
This has most likely something to do with the not so stable new puppeting.
Right now there a two somewhat quick fixes:
1. In your DB under puppet/name_quality must be a almost empty entry. You can try to remove this one entirely. However: This might only last util the next sync.
2. Another, more permanent fix (which will last syncs) is to fill this entry with `NULL`s.

I hope I could help :)

**Comment by iexos** [comment]
Thank you, that did help! Setting to null did not do the trick for me (got another error message) but deleting worked, I will see what happens on next launch

**Comment by hieronymousch** [comment]
have this problem as well, both in the docker as with normal mode... occurs every time I restart the bridge.

**Comment by hieronymousch** [comment]
Tried with postgres and seems to work now... but see log warnings [Jun  9, 2019 18:59:10] [Database/Puppet/WARN] Failed to insert xxxx@s.whatsapp.net: pq: invalid input syntax for integer: ""

**Comment by derjames** [comment]
@iexos
Do you remember the error message when you changed the values to null in the database?

**Comment by f1egmatik** [comment]
Workaround to start the bridge. 

cp mautrix-whatsapp.db mautrix-whatsapp.db.backup
sqlite3 mautrix-whatsapp.db
sqlite> UPDATE "puppet" SET "name_quality"='0', "custom_mxid" = '' WHERE "name_quality" = ''; 
<ctrl>+<d>

**Comment by iexos** [comment]
@derjames sorry cannot find it in the logs anymore

after restarting it still works, so deleting for me seems to be a permanent fix

**Comment by devilankur18** [comment]
upon testing with different numbers, found this issue and it stops completely working. had to remove mautrix-whatsapp.db and restart again to get it working.

[Database/Puppet/ERROR] Database scan failed: sql: Scan error on column index 4, name "name_quality": converting driver.Value type []uint8 ("") to a int64: invalid syntax

**Comment by hughwilliams94** [comment]
If I am running the bridge from the matrix-docker-ansible-deploy any idea, how I get at the db?

**Comment by Addono** [comment]
What I do is I manually SSH into the machine Matrix host and run:
```bash
sqlite3 /matrix/mautrix-whatsapp/mautrix-whatsapp.db
```

**Comment by hughwilliams94** [comment]
Hi, thanks for the reply.  I managed to work it out in the end, using essentially that method.
