### ISSUE TITLE
No Portal creation (or reinvite) on new message on WhatsApp side

### ISSUE THREAD

**Issue by krombel** [tulir/mautrix-whatsapp#7]
When you once either rejected the invite or left a portal room there is no way currently to reestablish a communication with a WhatsApp member

**Comment by ptman** [comment]
I was planning to file this issue myself, but you were faster.

**Comment by krombel** [comment]
An intermediate solution for one specific number:
1. run following sql on `mautrix-whatsapp.db` (default):
```sql
SELECT mxid FROM portals WHERE jid = "<number>@s.whatsapp.net";
DELETE FROM portals WHERE jid = "<number>@s.whatsapp.net";
```
2. stop the bridge
3. remove the room of the `SELECT`-query above from mx-state.json
4. start the bridge again which will invite you to a new room you can use to chat with the person in question
