### ISSUE TITLE
Cannot find package on go build

### ISSUE THREAD

**Issue by jonesmat** [tulir/mautrix-whatsapp#72]
I performed the following steps attempting to setup `mautrix-whatsapp` and get the error shown below.

1. Cloned the repo at https://github.com/tulir/mautrix-whatsapp.git into ~/go/src/
2. cd into `~/go/src/maultrix-whatsapp`
3. Run `go build`

I get the following errors:

> main.go:32:2: cannot find package "maunium.net/go/mautrix-whatsapp/config" in any of:
>         /usr/lib/go-1.10/src/maunium.net/go/mautrix-whatsapp/config (from $GOROOT)
>         /home/mattjones/go/src/maunium.net/go/mautrix-whatsapp/config (from $GOPATH)
> commands.go:31:2: cannot find package "maunium.net/go/mautrix-whatsapp/database" in any of:
>         /usr/lib/go-1.10/src/maunium.net/go/mautrix-whatsapp/database (from $GOROOT)
>         /home/mattjones/go/src/maunium.net/go/mautrix-whatsapp/database (from $GOPATH)
> main.go:30:2: cannot find package "maunium.net/go/mautrix-whatsapp/database/upgrades" in any of:
>         /usr/lib/go-1.10/src/maunium.net/go/mautrix-whatsapp/database/upgrades (from $GOROOT)
>         /home/mattjones/go/src/maunium.net/go/mautrix-whatsapp/database/upgrades (from $GOPATH)
> commands.go:32:2: cannot find package "maunium.net/go/mautrix-whatsapp/types" in any of:
>         /usr/lib/go-1.10/src/maunium.net/go/mautrix-whatsapp/types (from $GOROOT)
>         /home/mattjones/go/src/maunium.net/go/mautrix-whatsapp/types (from $GOPATH)
> commands.go:33:2: cannot find package "maunium.net/go/mautrix-whatsapp/whatsapp-ext" in any of:
>         /usr/lib/go-1.10/src/maunium.net/go/mautrix-whatsapp/whatsapp-ext (from $GOROOT)
>         /home/mattjones/go/src/maunium.net/go/mautrix-whatsapp/whatsapp-ext (from $GOPATH)

I'm not familiar with golang, so this is likely something simple.  Advice would be nice. 

Thanks!

**Comment by olmari** [comment]
Along updates, Go versiom 1.12 was made an requirement, you seem to have 1.10.

**Comment by jonesmat** [comment]
Bah!  Thanks!  I intended to install version 1.12 but must have pulled down the wrong tar.
