### ISSUE TITLE
DB-Migration failure

### ISSUE THREAD

**Issue by ugs9fsy71cb** [tulir/mautrix-whatsapp#75]
[Jun 20, 2019 09:56:48] [DEBUG] Initializing state store
[Jun 20, 2019 09:56:48] [DEBUG] Initializing database
[Jun 20, 2019 09:56:48] [DEBUG] Initializing Matrix event processor
[Jun 20, 2019 09:56:48] [DEBUG] Initializing Matrix event handler
[Jun 20, 2019 09:56:48] [INFO] Bridge initialization complete, starting...
[Jun 20, 2019 09:56:48] [Database/Upgrade/INFO] Database currently on v8, latest: v8
[Jun 20, 2019 09:56:48] [DEBUG] Starting application service HTTP server
[Jun 20, 2019 09:56:48] [DEBUG] Starting event processor
[Jun 20, 2019 09:56:48] [INFO] Bridge started!
[Jun 20, 2019 09:56:48] [Matrix/INFO] Listening on 0.0.0.0:8080
[Jun 20, 2019 09:56:48] [DEBUG] Updating bot profile
[Jun 20, 2019 09:56:48] [Database/Puppet/ERROR] Database scan failed: sql: Scan error on column index 4, name "name_quality": converting driver.Value type []uint8 ("") to a int64: invalid syntax
[Jun 20, 2019 09:56:48] [Database/Puppet/ERROR] Database scan failed: sql: Scan error on column index 4, name "name_quality": converting driver.Value type []uint8 ("") to a int64: invalid syntax

**Comment by Ma27** [comment]
A workaround is described here: https://github.com/tulir/mautrix-whatsapp/issues/69#issuecomment-500389802
