### ISSUE TITLE
use case : Whatsapp based 'customer support'

### ISSUE THREAD

**Issue by binooetomo** [tulir/mautrix-whatsapp#78]
Dear All.

I just found matrix today, and jump to mautrix-whatsapp.
Kindly please tell me if mautrix-whatsapp is fit my case.

Let's say currently I have working in house IRC server, with some user registered.
I also have one whatsapp account.

What I want is , whenever a Customer text my whatsapp account :
1. system will broad cast the text to all my CS (customer support team) member.
2. One of CS will send kind of ack text as respond
3. and for all next texting, system will 'tunnel' that customer to one CS that send first ack text.

Is mautrix-whatsapp fit my need ?
If so, is there any docs on how to doing it?

Sincerely
-bino-

**Comment by tulir** [comment]
Customer support and other similar use cases are possible nowadays with the [relay mode](https://github.com/tulir/mautrix-whatsapp/blob/master/example-config.yaml#L155-L173). https://github.com/maubot/supportportal might also help.
