### ISSUE TITLE
Mautrix-whatsapp not connecting to whatsapp

### ISSUE THREAD

**Issue by julianuu** [tulir/mautrix-whatsapp#79]
Hi! Sometimes when I start mautrix-whatsapp, it doesn't connect to my whatsapp instance. I can't chat and running 'reconnect' tells me I would have to login first.

Might be that restarting mautrix-whatsapp fixed this sometimes, but currently it does not.

I have whatsapp running in an android-emulator on my computer (which also makes logging in again a bit cumbersome).

Log:
```
[DEBUG] Initializing state store
[DEBUG] Initializing database
[DEBUG] Initializing Matrix event processor
[DEBUG] Initializing Matrix event handler
[INFO] Bridge initialization complete, starting...
[Database/Upgrade/INFO] Database currently on v8, latest: v8
[DEBUG] Starting application service HTTP server
[DEBUG] Starting event processor
[INFO] Bridge started!
[DEBUG] Updating bot profile
[DEBUG] Starting users
[Matrix/INFO] Listening on 0.0.0.0:8080
[DEBUG] Starting custom puppets
```

**Comment by Ma27** [comment]
Are you on the latest revision? I had some similar problems last week and upgrading to 29f5ae45c4b22f463003b23e355b951831f08b3e helped :)

**Comment by julianuu** [comment]
Actually no I am not. Unfortunately I can't really test until in a few weeks, but I'll try then, thanks!

**Comment by rogora** [comment]
Hello! I think this issue should be reopened, as I notice the same behavior also with the latest revision

**Comment by tulir** [comment]
This might be fixed with the latest commit that fixes some unexpected logout/session forget cases

**Comment by julianuu** [comment]
Unfortunately the symptoms haven't changed a lot, i.e. I sometimes can't reconnect after restarting the pc that runs whatsapp (in an emulator). What has changed is the error message. After restarting the bridge it works again

> 08:43:55 …/DEBUG] JSON message: ["Blocklist",{"id":1,"blocklist":[]}]
> 08:43:55 …/DEBUG] JSON message: ["Stream","update",true,"0.3.4479"]
> 08:43:55 …/DEBUG] JSON message: ["Props",{"webCleanIncomingFilename":1,"webRestoreFromCache":false,"wsOverrideTimeout":3,"wsOverrideAttempts":2,"wsOverride":true,"fbCrashlog":true,"bucket":"","gifSearch":"tenor","SPAM":true,"SET_BLOCK":true,"MESSAGE_INFO":true,"maxFileSize":100,"media":64,"maxSubject":25,"maxParticipants":257,"videoMaxEdge":960,"imageMaxKBytes":1024,"edit":1,"imageMaxEdge":1600,"suspiciousLinks":1,"fwdUiStartTs":1531267200,"stickers":1,"restrictGroups":1,"announceGroups":1001,"quickForwardRestrictEnabled":0,"groupDescLength":512,"multicastLimitGlobal":5,"finalLiveLocation":1,"frequentlyForwardedMax":5,"mmsMediaKeyTTL":172800}]
> 08:43:55 …/DEBUG] JSON message: ["Conn",{"protoVersion":[0,17],"binVersion":10,"phone":{"wa_version":"2.19.142","mcc":"310","mnc":"260","os_version":"9","device_manufacturer":"unknown","device_model":"generic_x86","os_build_number":"sdk_phone_x86-userdebug 9 PSR1.180720.012 4923214 test-keys"},"features":{"URL":true,"FLAGS":"…"},"pushname":"…"}]
> 08:43:55 …/DEBUG] JSON message: ["Props",{"webCleanIncomingFilename":1,"webRestoreFromCache":false,"wsOverrideTimeout":3,"wsOverrideAttempts":2,"wsOverride":true,"fbCrashlog":true,"bucket":"","gifSearch":"tenor","SPAM":true,"SET_BLOCK":true,"MESSAGE_INFO":true,"maxFileSize":100,"media":64,"maxSubject":25,"maxParticipants":257,"videoMaxEdge":960,"imageMaxKBytes":1024,"edit":1,"imageMaxEdge":1600,"suspiciousLinks":1,"fwdUiStartTs":1531267200,"stickers":1,"restrictGroups":1,"announceGroups":1001,"quickForwardRestrictEnabled":0,"groupDescLength":512,"multicastLimitGlobal":5,"finalLiveLocation":1,"frequentlyForwardedMax":5,"mmsMediaKeyTTL":172800}]
> 08:43:57 …/INFO] Syncing puppet info from contacts
> 08:43:57 …/INFO] Syncing puppet info from contacts
> 08:43:57 …/INFO] Chat list received
> 08:43:57 …/INFO] Reading chat list
> 08:43:57 …/INFO] Read chat list, updating user-portal mapping
> 08:43:57 …/INFO] Syncing portals
> 08:43:57 …/INFO] Syncing portal for @julian:matrix.wg1oglinks.duckdns.org
> 08:43:57 …/INFO] Chat list received
> 08:43:57 …/INFO] Reading chat list
> 08:43:57 …/INFO] Read chat list, updating user-portal mapping
> 08:43:57 …/INFO] Syncing portals
> 08:43:57 …/INFO] Syncing portal for @julian:matrix.wg1oglinks.duckdns.org
> 08:43:58 …/DEBUG] Not backfilling: no new messages
> 08:43:58 …/INFO] Syncing portal for @julian:matrix.wg1oglinks.duckdns.org
> 08:43:58 …/DEBUG] Not backfilling: no new messages
> 08:43:58 …/INFO] Finished syncing portals
> 08:43:58 …/DEBUG] Not backfilling: no new messages
> 08:43:58 …/INFO] Syncing portal for @julian:matrix.wg1oglinks.duckdns.org
> 08:43:58 …/DEBUG] Not backfilling: no new messages
> 08:43:58 …/INFO] Finished syncing portals
> 08:43:59 …/ERROR] WhatsApp JSON parse error: json: cannot unmarshal object into Go value of type whatsappExt.JSONMessage
> 08:43:59 …/DEBUG] JSON message: {"status":401}
> 08:44:20 …/INFO] Finished syncing puppet info from contacts

**Comment by julianuu** [comment]
I haven't had this problem anymore for a while now, so looks like its fixed.
