### ISSUE TITLE
Delay send connection failed message if it quickly restored

### ISSUE THREAD

**Issue by MurzNN** [tulir/mautrix-whatsapp#85]
I have notice messages from bot 1-3 times every day:

> Your WhatsApp connection failed: websocket: close 1006 (abnormal closure): unexpected EOF. Reconnecting...

And after 0-3 seconds:

> Reconnected successfully

Will be good to delay sending connection failed messages for some (30?) seconds, and suppress sending, if connection is successfully restored in this time.

**Comment by tulir** [comment]
https://github.com/tulir/mautrix-whatsapp/blob/master/example-config.yaml#L98-L100
