### ISSUE TITLE
Unknown error while reconnecting: init responded with %!d(float64=400)

### ISSUE THREAD

**Issue by dreamflasher** [tulir/mautrix-whatsapp#87]
I successfully logged in, and it synced a few chats, then it asks to manually reconnect which results in:

`Unknown error while reconnecting: init responded with %!d(float64=400)`

**Comment by dreamflasher** [comment]
Restarting the docker container helped.

**Comment by tulir** [comment]
The current correct solution is `disconnect` + `reconnect`. The proper solution is making the bridge do that automatically.
