### ISSUE TITLE
Bot command for invite new WhatsApp user to WhatsApp group

### ISSUE THREAD

**Issue by MurzNN** [tulir/mautrix-whatsapp#88]
Seems now there are no ways to invite new WhatsApp user to WhatsApp group via bridge?
I try to invite Matrix AS virtual user, matched to needed WhatsApp number, but it stay in invite state.
Can this feature been implemented? Something like `!wa invite <whatsapp_number>`

**Comment by tulir** [comment]
It hasn't been implemented yet, but invites will of course be bridged as invites.

**Comment by tulir** [comment]
Inviting whatsapp puppets should work as of 326293303d31ef7f4413e097ee207e6793f91dab
