### ISSUE TITLE
Silently disconnects

### ISSUE THREAD

**Issue by mrjohnson22** [tulir/mautrix-whatsapp#89]
Sometimes, the bridge disconnects from WhatsApp without the bot saying that it disconnected. This means WhatsApp messages will be missed until you get suspicious at not having received any WA messages lately and think to run "reconnect" in the bot chatroom.

Evidence that a silent disconnect happened is that the bot's latest message wasn't something indicating a disconnect, yet running "reconnect" in the bot chatroom has the bot respond with "Reconnected successfully" instead of "You were already connected". Doing this allows the bot to sync some missed messages, but not all of them. Restarting the bridge seems to sync any messages a reconnect didn't find, but this will cause those messages to appear after the messages that were synced by "reconnect", even if those messages were really sent before the previously-synced ones.

This has happened a few times while my bridge was connected to two WA clients: one on a virtual Android on a server & one on a real phone. The disconnect has happened for both accounts.

**Comment by mrjohnson22** [comment]
All of the recent fixes may have resolved this.

**Comment by Yajo** [comment]
On which release?

**Comment by mrjohnson22** [comment]
Not sure, but it was such a long time ago that the problem has likely since been fixed.

Since I'm the one who opened this case and haven't run into the problem again, I'll just close this.

**Comment by topikuning** [comment]
actually it happened again in relaybot mode
