### ISSUE TITLE
Can't send messages

### ISSUE THREAD

**Issue by Cogitri** [tulir/mautrix-whatsapp#91]
Hello,

receiving messages works just fine, however sending them fails with:

```
[Aug 26, 2019 14:46:57] [StateStore/WARN] Failed to scan membership of @whatsappbot:matrix.exqa.de in !<roomid>:matrix.exqa.de: sql: no rows in result set
```

**Comment by tulir** [comment]
That's a warning (that I should probably remove), not an error. Does it fail consistently?

**Comment by Cogitri** [comment]
That happened consistently, but changing mautrix-whatsapp to run as the same user as synapse apparently fixed that (or I just had permission errors somewhere that were fixed by that?). Anyway, seems to be user error on my part.

Thank you very much for this project!
