### ISSUE TITLE
After disconnect invalid session

### ISSUE THREAD

**Issue by Schutzwurst** [tulir/mautrix-whatsapp#94]
Hello for a few days I am having the issue, that when the bridge disconnects over night, then I cannot reconnect the bridge. When i directly try to reconnect after the disconnect I usually get the Error 400 and after trying to reconnect after i gave the bot the command to disconnect I get no response. Here you can see the error it prints, when trying to reconnect after the command disconnect. 

`[Aug 28, 2019 05:29:48] [User/@schutzwurst:matrix.urbanke.tirol/DEBUG] Got invalid session error when reconnecting, but user has session. Retrying using RestoreWithSession()... 
[Aug 28, 2019 05:30:09] [Matrix/Events/ERROR] Panic in Matrix event handler: interface conversion: interface {} is nil, not float64 (event content: {"sender":"@schutzwurst:matrix.urbanke.tirol","type":"m.room.message","origin_server_ts":xxxxx,"event_id":"$xxxxxxxxx:matrix.urbanke.tirol","room_id":"xxxxxxxxxxx:matrix.urbanke.tirol","content":{"msgtype":"m.text","body":"reconnect"},"unsigned":{"age":105,"m.relations":{"m.annotation":{"chunk":[],"limited":false,"count":0},"m.reference":{"chunk":[],"limited":false,"count":0},"m.replace":{"chunk":[],"limited":false,"count":0}}},"invite_room_state":null}) `

**Comment by tulir** [comment]
Pushed a update that should make those panics display stack traces (db53b95ab116c559f433e4744f62617b8970a2ba). If you can still reproduce the problem, please post the stack trace.

**Comment by Schutzwurst** [comment]
Thanks! Haven't had this issue since. Will reopen it with the stack trace, if it will ever happen again.

**Comment by Schutzwurst** [comment]
Yesterday at night I got the error again. 

Here is the stack trace:

```goroutine 141 [running]:
runtime/debug.Stack(0xadf760, 0xc0004b4000, 0xc000344400)
    /usr/lib/go-1.12/src/runtime/debug/stack.go:24 +0x9d
maunium.net/go/mautrix-appservice.(*EventProcessor).callHandler.func1(0xc0004b4000, 0xc0001a68d0)
    /var/lib/matrix-synapse/go/pkg/mod/maunium.net/go/mautrix-appservice@v0.1.0-alpha.3.0.20190830063827-e7dcd7e42e7c/eventprocessor.go:58 +0xa9
panic(0xad26a0, 0xc000348360)
    /usr/lib/go-1.12/src/runtime/panic.go:522 +0x1b5
github.com/Rhymen/go-whatsapp.(*Conn).getAdminLoginResponseError(0xc00026c0c0, 0xc000348330, 0xb7cda7, 0x6)
    /var/lib/matrix-synapse/go/pkg/mod/github.com/tulir/go-whatsapp@v0.0.2-0.20190825095058-bb85c7370264/session.go:453 +0x3fd
github.com/Rhymen/go-whatsapp.(*Conn).Restore(0xc00026c0c0, 0x0, 0x0)
    /var/lib/matrix-synapse/go/pkg/mod/github.com/tulir/go-whatsapp@v0.0.2-0.20190825095058-bb85c7370264/session.go:388 +0x1c46
github.com/Rhymen/go-whatsapp.(*Conn).RestoreWithSession(0xc00026c0c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)    /var/lib/matrix-synapse/go/pkg/mod/github.com/tulir/go-whatsapp@v0.0.2-0.20190825095058-bb85c7370264/session.go:305 +0x101
main.(*CommandHandler).CommandReconnect(0xc000095ec0, 0xc0001d2370)
    /opt/matrix_bridges/mautrix-whatsapp/commands.go:207 +0x5e4
main.(*CommandHandler).Handle(0xc000095ec0, 0xc00036c720, 0x28, 0xc00026e620, 0xc0004be370, 0x9)
    /opt/matrix_bridges/mautrix-whatsapp/commands.go:90 +0x810
main.(*MatrixHandler).HandleMessage(0xc0001a6900, 0xc0004b4000)
    /opt/matrix_bridges/mautrix-whatsapp/matrix.go:188 +0x541
maunium.net/go/mautrix-appservice.(*EventProcessor).callHandler(0xc0001a68d0, 0xc00017bb30, 0xc0004b4000)
    /var/lib/matrix-synapse/go/pkg/mod/maunium.net/go/mautrix-appservice@v0.1.0-alpha.3.0.20190830063827-e7dcd7e42e7c/eventprocessor.go:61 +0x60
created by maunium.net/go/mautrix-appservice.(*EventProcessor).Start
    /var/lib/matrix-synapse/go/pkg/mod/maunium.net/go/mautrix-appservice@v0.1.0-alpha.3.0.20190830063827-e7dcd7e42e7c/eventprocessor.go:75 +0x66
```

**Comment by tulir** [comment]
That commit should stop the panic and give the correct error message
