### ISSUE TITLE
Community feature does not work?

### ISSUE THREAD

**Issue by mithodin** [tulir/mautrix-whatsapp#96]
In the configuration file, there is an option `community_template` and the documentation in the example config seems to suggest that the bridge bot should create a community to put all the chats into. However, that does not seem to happen, at least as far as I can tell. Has that feature been dropped? Have I configured my synapse/mautrix-whatsapp wrong?

**Comment by deepbluev7** [comment]
Can your bot user create communities? You may need to give it admin rights or allow users other than admins to create communities.

**Comment by mithodin** [comment]
The bot wasn't an admin, so I guess it wasn't allowed to create the community. Can I somehow trigger that now?

**Comment by deepbluev7** [comment]
I think it will just create the community, if you restart the bridge, but maybe you also need to trigger a sync.

**Comment by mithodin** [comment]
Yeah, that did the trick. Thank you!
